/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

#include <$(proc)/api.h>
#include <$(proc)/id.h>
#include <$(proc)/macros.h>
#include <$(proc)/grt.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef unsigned long otawa_kind_t;
typedef otawa_kind_t (*fun_t)($(proc)_inst_t *inst);

/*** function definition ***/

static otawa_kind_t otawa_kind_UNKNOWN($(proc)_inst_t *inst) {
	return 0;
}

$(foreach instructions)
static otawa_kind_t otawa_kind_$(IDENT)($(proc)_inst_t *inst) {
$(otawa_kind)
};

$(end)


/*** function table ***/
static fun_t kind_funs[] = {
	otawa_kind_UNKNOWN$(foreach instructions),
	otawa_kind_$(IDENT)$(end)
};

/**
 * Get the OTAWA kind of the instruction.
 * @return OTAWA kind.
 */
otawa_kind_t $(proc)_kind($(proc)_inst_t *inst) {
	return kind_funs[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif
