/* Generated by gliss-attr (117/07/07 16:19:42) copyright (c) 2009 IRIT - UPS */

#include <ppc/api.h>
#include <ppc/id.h>
#include <ppc/macros.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint32_t otawa_target_t;

typedef otawa_target_t (*target_fun_t)(ppc_inst_t *inst);



static otawa_target_t otawa_target_UNKNOWN(ppc_inst_t *inst)
{
        /* this code should also be used as default value if
        an instruction has no otawa_target field */
        return 0;
}

static otawa_target_t otawa_target_WRTEE_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_WRTEE_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TLBWE(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TLBSYNC(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TLBSX_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TLBRE(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TLBIVAX_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSYNC(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTDCR_D__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFDCR__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MBAR_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ICBT_D__RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_XOR__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_XOR_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ICBI_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBZ_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBTST_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBT_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBST_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBI_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBF_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBA_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TW_D_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFCR_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFZEO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFZEO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFZE__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFZE_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFMEO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFMEO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFME__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFME_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFEO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFEO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFE__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFE_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFCO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFCO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFC__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFC_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBF__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBF_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STWCX__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STWBRX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STSWI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STSWX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STHBRX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STWUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STWX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STHUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STHX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STBUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STBX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SRW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SRW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SRAWI__RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SRAWI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SRAW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SRAW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SLW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SLW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORC__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORC_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_OR__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_OR_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTSPR_D_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTMSR_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFSPR_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFMSR_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NOR__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NOR_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NEGO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NEGO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NEG__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NEG_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NAND__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NAND_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULLWO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULLWO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULLW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULLW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULHWU__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULHWU_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULHW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULHW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTSPR_S_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MCRXR_CRFD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTCRF_D_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFSPR_RD_S(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LWARX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LWBRX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LWZUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LWZX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHZUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHZX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHBRX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHAUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHAX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LBZUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LBZX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ISEL_RD__RD__R5B__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EXTSH__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EXTSH_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EXTSB__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EXTSB_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EQV__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EQV_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVWUO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVWUO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVWU__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVWU_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVWO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVWO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CNTLZW__RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CNTLZW_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPL_D_D_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMP_D_D_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDC__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDC_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_AND__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_AND_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDZEO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDZEO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDZE__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDZE_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDMEO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDMEO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDME__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDME_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDEO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDEO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDE__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDE_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDCO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDCO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDC__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDC_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDSS_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_XORIS_RD__RD__X(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_SUBFICS_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_STMW_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_STWU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_STW_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_STHU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_STH_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_STBU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_STB_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_SRWIS_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_SLWIS_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_RLWINM_RD__RD__D__D__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_RLWIMI_RD__RD__D__D__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_RLWIS_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_RLWS_RD__RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_ORIS_RD__RD__X(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_OR2IS_RD__X(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_OR2I_RD__X(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_MULL2I_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_MULLI_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_MCRF_CRD__CRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_LMW_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_LWZU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_LWZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_LIS_RD__X(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_LI_RD__X(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_LHZU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_LHZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_LHAU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_LHA_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_LBZU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_LBZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CRXOR_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CRORC_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CROR_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CRNOR_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CRNAND_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CREQV_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CRANDC_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CRAND_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CMPLI_CRD__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CMPL16I_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CMPI_CRD__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CMPHL16I_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CMPHL_CRD__RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CMPH16I_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CMPH_CRD__RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_CMP16I_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_BCS_X__X_08X(ppc_inst_t *inst) {
	return (PPC_E_BCS_X__X_08X___IADDR + (((int32_t)(PPC_E_BCS_X__X_08X_x_x_BD15)) << 1));

};

static otawa_target_t otawa_target_E_BS_08X(ppc_inst_t *inst) {
	return (PPC_E_BS_08X___IADDR + (((int32_t)(PPC_E_BS_08X_x_x_BD24)) << 1));

};

static otawa_target_t otawa_target_E_ADDICS_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_AND2IS__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_AND2I__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_ADDICS_RD__RD__D_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_ADDIS_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_ADD2IS_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_ADD2I__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_ADD16I_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_SUBIS_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_SUBF_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_SUB_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_STW_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_STH_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_STB_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_SRWI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_SRW_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_SRAWI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_SRAW_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_SLWI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_SLW_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_SC(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_RFI(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_RFDI(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_RFCI(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_OR_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_NOT_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_NEG_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_MULLW_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_MTLR_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_MTCTR_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_MTAR_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_MR_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_MFLR_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_MFCTR_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_MFAR_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_LI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_LWZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_LHZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_LBZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_EXTZH_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_EXTZB_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_EXTSH_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_EXTSB_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_CMPLI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_CMPL_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_CMPI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_CMPHL_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_CMPH_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_CMP_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_BTSTI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_BSETI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_BMSKI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BLRS(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BGENI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_BCTRS(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BCLRI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_BC_X__X__08X(ppc_inst_t *inst) {
	return (PPC_SE_BC_X__X__08X___IADDR + (((int32_t)(PPC_SE_BC_X__X__08X_x_x_BD8)) << 1));

};

static otawa_target_t otawa_target_SE_BS_08X(ppc_inst_t *inst) {
	return (PPC_SE_BS_08X___IADDR + (((int32_t)(PPC_SE_BS_08X_x_x_BD8)) << 1));

};

static otawa_target_t otawa_target_SE_ANDC_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_ANDI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_E_ANDS_RD__RD_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_ADDI_RD__D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SE_ADD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFAPIDI_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TLBSYNC_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TLBIE_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TLBIA(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RFI(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTSRIN_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTSR_D_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFSRIN_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFSR_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTSPR_D_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTMSR_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFSPR_RD_D_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFMSR_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFTB_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ISYNC(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EIEIO(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ECOWX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ECIWX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ICBI_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBZ_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBTST_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBT_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBST_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBI_RD__RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBF_RD__RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DCBA_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTFSFI__CRFD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTFSFI_CRFD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTFSF__D_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTFSF_D_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTFSB1__CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTFSB1_CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTFSB0__CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTFSB0_CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFFS__FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFFS_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MCRFS_CRFD_CRFD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FCTIWZ__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FCTIWZ_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FCTIW__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FCTIW_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FRSP__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FRSP_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FNABS__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FNABS_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FABS__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FABS_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FNEG__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FNEG_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMR__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMR_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FCMPU_CRFD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FCMPO_CRFD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FNMSUBS__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FNMSUBS_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FNMSUB__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FNMSUB_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMSUBS__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMSUBS_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMSUB__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMSUB_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FNMADDS__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FNMADDS_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FNMADD__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FNMADD_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMADDS__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMADDS_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMADD__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMADD_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FDIVS__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FDIVS_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FDIV__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FDIV_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMULS__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMULS_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMUL__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FMUL_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FSUBS__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FSUBS_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FSUB__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FSUB_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FADDS__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FADDS_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FADD__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_FADD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STFSUX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STFSU_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STFSX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STFS_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STFDUX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STFDU_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STFDX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STFD_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LFSUX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LFSU_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LFSX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LFS_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LFDUX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LFDU_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LFDX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LFD_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TWI_D_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TW_D_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SYNC(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STWCX__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LWARX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFSPR_RD_S_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTSPR_S_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MFCR_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ISEL_RD__RD__R5B__D_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MCRXR_CRFD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MTCRF_D_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MCRF_CRFD_CRFD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CRORC_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CRANDC_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CREQV_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CRNOR_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CRNAND_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CRXOR_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CROR_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CRAND_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SRAW__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SRAW_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SRAWI__RD_RD_D_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SRAWI_RD_RD_D_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SRW__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SRW_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SLW__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SLW_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RLWIMI__RD_RD_D_D_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RLWIMI_RD_RD_D_D_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RLWNM__RD_RD_RD_D_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RLWNM_RD_RD_RD_D_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RLWINM__RD_RD_D_D_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RLWINM_RD_RD_D_D_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CNTLZW__RD__RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CNTLZW_RD__RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EXTSH__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EXTSH_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EXTSB__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EXTSB_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EQV__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EQV_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NAND__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NAND_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NOR__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NOR_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_XORIS_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_XORI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_XOR__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_XOR_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDC__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDC_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDIS__RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDI__RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_AND__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_AND_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORC__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORC_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORIS_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_OR__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_OR_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPL_D_D_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPLI_D_D_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMP_D_D_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPI_D_D_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NEGO__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NEGO_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NEG__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NEG_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVWUO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVWUO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVWU__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVWU_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVWO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVWO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVW__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_DIVW_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULHWU__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULHWU_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULHW__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULHW_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULLI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULLWO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULLWO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULLW__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULLW_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFZEO__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFZEO_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFZE__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFZE_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFMEO__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFMEO_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFME__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFME_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFEO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFEO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFE__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFE_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFCO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFCO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFC__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFC_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFIC_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBFO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBF__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBF_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDZEO__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDZEO_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDZE__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDZE_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDMEO__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDMEO_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDME__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDME_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDEO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDEO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDE__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDE_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDCO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDCO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDC__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDC_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDIC__RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDIC_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDIS_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDSS_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STSWX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STSWI_RD_RD_D_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STMW_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STWBRX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STHBRX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STWUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STWU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STWX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STW_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STHUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STHU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STHX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STH_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STBUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STBU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STBX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STB_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LSWX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LSWI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LMW_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LWBRX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHBRX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LWZUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LWZU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LWZX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LWZ_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHAUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHAU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHAX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHA_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHZUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHZU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHZX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LHZ_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LBZUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LBZU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LBZX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LBZ_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SC(ppc_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BCLRL_D_D(ppc_inst_t *inst) {
	return 0;

};

static otawa_target_t otawa_target_BCLR_D_D(ppc_inst_t *inst) {
	return 0;

};

static otawa_target_t otawa_target_BCCTRL_D_D(ppc_inst_t *inst) {
	return 0;

};

static otawa_target_t otawa_target_BCCTR_D_D(ppc_inst_t *inst) {
	return 0;

};

static otawa_target_t otawa_target_BCLA_D_D_D(ppc_inst_t *inst) {
	return (((uint32_t)(((PPC_BCLA_D_D_D_x_x_x_BD_n) &  ((1 << 14) - 1)))) << 2);

};

static otawa_target_t otawa_target_BCL_D_D_D(ppc_inst_t *inst) {
	return (PPC_BCL_D_D_D___IADDR + (((int32_t)(PPC_BCL_D_D_D_x_x_x_BD_n)) << 2));

};

static otawa_target_t otawa_target_BCA_D_D_D(ppc_inst_t *inst) {
	return (((uint32_t)(((PPC_BCA_D_D_D_x_x_x_BD_n) &  ((1 << 14) - 1)))) << 2);

};

static otawa_target_t otawa_target_BC_D_D_D(ppc_inst_t *inst) {
	return (PPC_BC_D_D_D___IADDR + (((int32_t)(PPC_BC_D_D_D_x_x_x_BD_n)) << 2));

};

static otawa_target_t otawa_target_BLA_D(ppc_inst_t *inst) {
	return (((uint32_t)(((PPC_BLA_D_x_x_BRANCH_ADDR_n) &  ((1 << 24) - 1)))) << 2);

};

static otawa_target_t otawa_target_BL_0X08X(ppc_inst_t *inst) {
	return (PPC_BL_0X08X___IADDR + (((int32_t)(PPC_BL_0X08X_x_x_BRANCH_ADDR_n)) << 2));

};

static otawa_target_t otawa_target_BA_D(ppc_inst_t *inst) {
	return (((uint32_t)(((PPC_BA_D_x_x_BRANCH_ADDR_n) &  ((1 << 24) - 1)))) << 2);

};

static otawa_target_t otawa_target_B_D(ppc_inst_t *inst) {
	return (PPC_B_D___IADDR + (((int32_t)(PPC_B_D_x_x_BRANCH_ADDR_n)) << 2));

};




/* function table */
static target_fun_t ppc_target_table[] =
{
	otawa_target_UNKNOWN,
	otawa_target_WRTEE_D,
	otawa_target_WRTEE_RD,
	otawa_target_TLBWE,
	otawa_target_TLBSYNC,
	otawa_target_TLBSX_RD__RD,
	otawa_target_TLBRE,
	otawa_target_TLBIVAX_RD__RD,
	otawa_target_MSYNC,
	otawa_target_MTDCR_D__RD,
	otawa_target_MFDCR__RD__D,
	otawa_target_MBAR_D,
	otawa_target_ICBT_D__RD__RD,
	otawa_target_XOR__RD_RD_RD,
	otawa_target_XOR_RD_RD_RD,
	otawa_target_ICBI_RD_RD,
	otawa_target_DCBZ_RD_RD,
	otawa_target_DCBTST_RD_RD,
	otawa_target_DCBT_RD_RD,
	otawa_target_DCBST_RD_RD,
	otawa_target_DCBI_RD__RD,
	otawa_target_DCBF_RD__RD,
	otawa_target_DCBA_RD_RD,
	otawa_target_TW_D_RD_RD,
	otawa_target_MFCR_RD,
	otawa_target_SUBFZEO__RD_RD,
	otawa_target_SUBFZEO_RD_RD,
	otawa_target_SUBFZE__RD_RD,
	otawa_target_SUBFZE_RD_RD,
	otawa_target_SUBFMEO__RD_RD,
	otawa_target_SUBFMEO_RD_RD,
	otawa_target_SUBFME__RD_RD,
	otawa_target_SUBFME_RD_RD,
	otawa_target_SUBFEO__RD_RD_RD,
	otawa_target_SUBFEO_RD_RD_RD,
	otawa_target_SUBFE__RD_RD_RD,
	otawa_target_SUBFE_RD_RD_RD,
	otawa_target_SUBFCO__RD_RD_RD,
	otawa_target_SUBFCO_RD_RD_RD,
	otawa_target_SUBFC__RD_RD_RD,
	otawa_target_SUBFC_RD_RD_RD,
	otawa_target_SUBFO__RD_RD_RD,
	otawa_target_SUBFO_RD_RD_RD,
	otawa_target_SUBF__RD_RD_RD,
	otawa_target_SUBF_RD_RD_RD,
	otawa_target_STWCX__RD_RD_RD,
	otawa_target_STWBRX_RD_RD_RD,
	otawa_target_STSWI_RD_RD_D,
	otawa_target_STSWX_RD_RD_RD,
	otawa_target_STHBRX_RD_RD_RD,
	otawa_target_STWUX_RD_RD_RD,
	otawa_target_STWX_RD_RD_RD,
	otawa_target_STHUX_RD_RD_RD,
	otawa_target_STHX_RD_RD_RD,
	otawa_target_STBUX_RD_RD_RD,
	otawa_target_STBX_RD_RD_RD,
	otawa_target_SRW__RD_RD_RD,
	otawa_target_SRW_RD_RD_RD,
	otawa_target_SRAWI__RD_RD_D,
	otawa_target_SRAWI_RD_RD_D,
	otawa_target_SRAW__RD_RD_RD,
	otawa_target_SRAW_RD_RD_RD,
	otawa_target_SLW__RD_RD_RD,
	otawa_target_SLW_RD_RD_RD,
	otawa_target_ORC__RD_RD_RD,
	otawa_target_ORC_RD_RD_RD,
	otawa_target_OR__RD_RD_RD,
	otawa_target_OR_RD_RD_RD,
	otawa_target_MTSPR_D_RD,
	otawa_target_MTMSR_RD,
	otawa_target_MFSPR_RD_D,
	otawa_target_MFMSR_RD,
	otawa_target_NOR__RD_RD_RD,
	otawa_target_NOR_RD_RD_RD,
	otawa_target_NEGO__RD_RD,
	otawa_target_NEGO_RD_RD,
	otawa_target_NEG__RD_RD,
	otawa_target_NEG_RD_RD,
	otawa_target_NAND__RD_RD_RD,
	otawa_target_NAND_RD_RD_RD,
	otawa_target_MULLWO__RD_RD_RD,
	otawa_target_MULLWO_RD_RD_RD,
	otawa_target_MULLW__RD_RD_RD,
	otawa_target_MULLW_RD_RD_RD,
	otawa_target_MULHWU__RD_RD_RD,
	otawa_target_MULHWU_RD_RD_RD,
	otawa_target_MULHW__RD_RD_RD,
	otawa_target_MULHW_RD_RD_RD,
	otawa_target_MTSPR_S_RD,
	otawa_target_MCRXR_CRFD,
	otawa_target_MTCRF_D_RD,
	otawa_target_MFSPR_RD_S,
	otawa_target_LWARX_RD_RD_RD,
	otawa_target_LWBRX_RD_RD_RD,
	otawa_target_LWZUX_RD_RD_RD,
	otawa_target_LWZX_RD_RD_RD,
	otawa_target_LHZUX_RD_RD_RD,
	otawa_target_LHZX_RD_RD_RD,
	otawa_target_LHBRX_RD_RD_RD,
	otawa_target_LHAUX_RD_RD_RD,
	otawa_target_LHAX_RD_RD_RD,
	otawa_target_LBZUX_RD_RD_RD,
	otawa_target_LBZX_RD_RD_RD,
	otawa_target_ISEL_RD__RD__R5B__D,
	otawa_target_EXTSH__RD_RD,
	otawa_target_EXTSH_RD_RD,
	otawa_target_EXTSB__RD_RD,
	otawa_target_EXTSB_RD_RD,
	otawa_target_EQV__RD_RD_RD,
	otawa_target_EQV_RD_RD_RD,
	otawa_target_DIVWUO__RD_RD_RD,
	otawa_target_DIVWUO_RD_RD_RD,
	otawa_target_DIVWU__RD_RD_RD,
	otawa_target_DIVWU_RD_RD_RD,
	otawa_target_DIVWO__RD_RD_RD,
	otawa_target_DIVWO_RD_RD_RD,
	otawa_target_DIVW__RD_RD_RD,
	otawa_target_DIVW_RD_RD_RD,
	otawa_target_CNTLZW__RD__RD,
	otawa_target_CNTLZW_RD__RD,
	otawa_target_CMPL_D_D_RD_RD,
	otawa_target_CMP_D_D_RD_RD,
	otawa_target_ANDC__RD_RD_RD,
	otawa_target_ANDC_RD_RD_RD,
	otawa_target_AND__RD_RD_RD,
	otawa_target_AND_RD_RD_RD,
	otawa_target_ADDZEO__RD_RD,
	otawa_target_ADDZEO_RD_RD,
	otawa_target_ADDZE__RD_RD,
	otawa_target_ADDZE_RD_RD,
	otawa_target_ADDMEO__RD_RD,
	otawa_target_ADDMEO_RD_RD,
	otawa_target_ADDME__RD_RD,
	otawa_target_ADDME_RD_RD,
	otawa_target_ADDEO__RD_RD_RD,
	otawa_target_ADDEO_RD_RD_RD,
	otawa_target_ADDE__RD_RD_RD,
	otawa_target_ADDE_RD_RD_RD,
	otawa_target_ADDCO__RD_RD_RD,
	otawa_target_ADDCO_RD_RD_RD,
	otawa_target_ADDC__RD_RD_RD,
	otawa_target_ADDC_RD_RD_RD,
	otawa_target_ADDSS_RD_RD_RD,
	otawa_target_E_XORIS_RD__RD__X,
	otawa_target_E_SUBFICS_RD__RD__D,
	otawa_target_E_STMW_RD__D_LP_RD_RP_,
	otawa_target_E_STWU_RD__D_LP_RD_RP_,
	otawa_target_E_STW_RD__D_LP_RD_RP_,
	otawa_target_E_STHU_RD__D_LP_RD_RP_,
	otawa_target_E_STH_RD__D_LP_RD_RP_,
	otawa_target_E_STBU_RD__D_LP_RD_RP_,
	otawa_target_E_STB_RD__D_LP_RD_RP_,
	otawa_target_E_SRWIS_RD__RD__D,
	otawa_target_E_SLWIS_RD__RD__D,
	otawa_target_E_RLWINM_RD__RD__D__D__D,
	otawa_target_E_RLWIMI_RD__RD__D__D__D,
	otawa_target_E_RLWIS_RD__RD__D,
	otawa_target_E_RLWS_RD__RD__RD,
	otawa_target_E_ORIS_RD__RD__X,
	otawa_target_E_OR2IS_RD__X,
	otawa_target_E_OR2I_RD__X,
	otawa_target_E_MULL2I_RD__D,
	otawa_target_E_MULLI_RD__RD__D,
	otawa_target_E_MCRF_CRD__CRD,
	otawa_target_E_LMW_RD__D_LP_RD_RP_,
	otawa_target_E_LWZU_RD__D_LP_RD_RP_,
	otawa_target_E_LWZ_RD__D_LP_RD_RP_,
	otawa_target_E_LIS_RD__X,
	otawa_target_E_LI_RD__X,
	otawa_target_E_LHZU_RD__D_LP_RD_RP_,
	otawa_target_E_LHZ_RD__D_LP_RD_RP_,
	otawa_target_E_LHAU_RD__D_LP_RD_RP_,
	otawa_target_E_LHA_RD__D_LP_RD_RP_,
	otawa_target_E_LBZU_RD__D_LP_RD_RP_,
	otawa_target_E_LBZ_RD__D_LP_RD_RP_,
	otawa_target_E_CRXOR_CRBD__CRBD__CRBD,
	otawa_target_E_CRORC_CRBD__CRBD__CRBD,
	otawa_target_E_CROR_CRBD__CRBD__CRBD,
	otawa_target_E_CRNOR_CRBD__CRBD__CRBD,
	otawa_target_E_CRNAND_CRBD__CRBD__CRBD,
	otawa_target_E_CREQV_CRBD__CRBD__CRBD,
	otawa_target_E_CRANDC_CRBD__CRBD__CRBD,
	otawa_target_E_CRAND_CRBD__CRBD__CRBD,
	otawa_target_E_CMPLI_CRD__RD__D,
	otawa_target_E_CMPL16I_RD__D,
	otawa_target_E_CMPI_CRD__RD__D,
	otawa_target_E_CMPHL16I_RD__D,
	otawa_target_E_CMPHL_CRD__RD__RD,
	otawa_target_E_CMPH16I_RD__D,
	otawa_target_E_CMPH_CRD__RD__RD,
	otawa_target_E_CMP16I_RD__D,
	otawa_target_E_BCS_X__X_08X,
	otawa_target_E_BS_08X,
	otawa_target_E_ADDICS_RD__RD__D,
	otawa_target_E_AND2IS__RD__D,
	otawa_target_E_AND2I__RD__D,
	otawa_target_E_ADDICS_RD__RD__D_0,
	otawa_target_E_ADDIS_RD__RD__D,
	otawa_target_E_ADD2IS_RD__D,
	otawa_target_E_ADD2I__RD__D,
	otawa_target_E_ADD16I_RD__RD__D,
	otawa_target_SE_SUBIS_RD__D,
	otawa_target_SE_SUBF_RD__RD,
	otawa_target_SE_SUB_RD__RD,
	otawa_target_SE_STW_RD__D_LP_RD_RP_,
	otawa_target_SE_STH_RD__D_LP_RD_RP_,
	otawa_target_SE_STB_RD__D_LP_RD_RP_,
	otawa_target_SE_SRWI_RD__D,
	otawa_target_SE_SRW_RD__RD,
	otawa_target_SE_SRAWI_RD__D,
	otawa_target_SE_SRAW_RD__RD,
	otawa_target_SE_SLWI_RD__D,
	otawa_target_SE_SLW_RD__RD,
	otawa_target_SE_SC,
	otawa_target_SE_RFI,
	otawa_target_SE_RFDI,
	otawa_target_SE_RFCI,
	otawa_target_SE_OR_RD__RD,
	otawa_target_SE_NOT_RD,
	otawa_target_SE_NEG_RD,
	otawa_target_SE_MULLW_RD__RD,
	otawa_target_SE_MTLR_RD,
	otawa_target_SE_MTCTR_RD,
	otawa_target_SE_MTAR_RD__RD,
	otawa_target_SE_MR_RD__RD,
	otawa_target_SE_MFLR_RD,
	otawa_target_SE_MFCTR_RD,
	otawa_target_SE_MFAR_RD__RD,
	otawa_target_SE_LI_RD__D,
	otawa_target_SE_LWZ_RD__D_LP_RD_RP_,
	otawa_target_SE_LHZ_RD__D_LP_RD_RP_,
	otawa_target_SE_LBZ_RD__D_LP_RD_RP_,
	otawa_target_SE_EXTZH_RD,
	otawa_target_SE_EXTZB_RD,
	otawa_target_SE_EXTSH_RD,
	otawa_target_SE_EXTSB_RD,
	otawa_target_SE_CMPLI_RD__D,
	otawa_target_SE_CMPL_RD__RD,
	otawa_target_SE_CMPI_RD__D,
	otawa_target_SE_CMPHL_RD__RD,
	otawa_target_SE_CMPH_RD__RD,
	otawa_target_SE_CMP_RD__RD,
	otawa_target_SE_BTSTI_RD__D,
	otawa_target_SE_BSETI_RD__D,
	otawa_target_SE_BMSKI_RD__D,
	otawa_target_BLRS,
	otawa_target_BGENI_RD__D,
	otawa_target_SE_BCTRS,
	otawa_target_BCLRI_RD__D,
	otawa_target_SE_BC_X__X__08X,
	otawa_target_SE_BS_08X,
	otawa_target_SE_ANDC_RD__RD,
	otawa_target_SE_ANDI_RD__D,
	otawa_target_E_ANDS_RD__RD_,
	otawa_target_SE_ADDI_RD__D,
	otawa_target_SE_ADD_RD_RD,
	otawa_target_MFAPIDI_RD__RD,
	otawa_target_TLBSYNC_0,
	otawa_target_TLBIE_RD,
	otawa_target_TLBIA,
	otawa_target_RFI,
	otawa_target_MTSRIN_RD_RD,
	otawa_target_MTSR_D_RD,
	otawa_target_MFSRIN_RD_RD,
	otawa_target_MFSR_RD_D,
	otawa_target_MTSPR_D_RD_0,
	otawa_target_MTMSR_RD_0,
	otawa_target_MFSPR_RD_D_0,
	otawa_target_MFMSR_RD_0,
	otawa_target_MFTB_RD_D,
	otawa_target_ISYNC,
	otawa_target_EIEIO,
	otawa_target_ECOWX_RD_RD_RD,
	otawa_target_ECIWX_RD_RD_RD,
	otawa_target_ICBI_RD_RD_0,
	otawa_target_DCBZ_RD_RD_0,
	otawa_target_DCBTST_RD_RD_0,
	otawa_target_DCBT_RD_RD_0,
	otawa_target_DCBST_RD_RD_0,
	otawa_target_DCBI_RD__RD_0,
	otawa_target_DCBF_RD__RD_0,
	otawa_target_DCBA_RD_RD_0,
	otawa_target_MTFSFI__CRFD_D,
	otawa_target_MTFSFI_CRFD_D,
	otawa_target_MTFSF__D_FRD,
	otawa_target_MTFSF_D_FRD,
	otawa_target_MTFSB1__CRBD,
	otawa_target_MTFSB1_CRBD,
	otawa_target_MTFSB0__CRBD,
	otawa_target_MTFSB0_CRBD,
	otawa_target_MFFS__FRD,
	otawa_target_MFFS_FRD,
	otawa_target_MCRFS_CRFD_CRFD,
	otawa_target_FCTIWZ__FRD_FRD,
	otawa_target_FCTIWZ_FRD_FRD,
	otawa_target_FCTIW__FRD_FRD,
	otawa_target_FCTIW_FRD_FRD,
	otawa_target_FRSP__FRD_FRD,
	otawa_target_FRSP_FRD_FRD,
	otawa_target_FNABS__FRD_FRD,
	otawa_target_FNABS_FRD_FRD,
	otawa_target_FABS__FRD_FRD,
	otawa_target_FABS_FRD_FRD,
	otawa_target_FNEG__FRD_FRD,
	otawa_target_FNEG_FRD_FRD,
	otawa_target_FMR__FRD_FRD,
	otawa_target_FMR_FRD_FRD,
	otawa_target_FCMPU_CRFD_FRD_FRD,
	otawa_target_FCMPO_CRFD_FRD_FRD,
	otawa_target_FNMSUBS__FRD_FRD_FRD_FRD,
	otawa_target_FNMSUBS_FRD_FRD_FRD_FRD,
	otawa_target_FNMSUB__FRD_FRD_FRD_FRD,
	otawa_target_FNMSUB_FRD_FRD_FRD_FRD,
	otawa_target_FMSUBS__FRD_FRD_FRD_FRD,
	otawa_target_FMSUBS_FRD_FRD_FRD_FRD,
	otawa_target_FMSUB__FRD_FRD_FRD_FRD,
	otawa_target_FMSUB_FRD_FRD_FRD_FRD,
	otawa_target_FNMADDS__FRD_FRD_FRD_FRD,
	otawa_target_FNMADDS_FRD_FRD_FRD_FRD,
	otawa_target_FNMADD__FRD_FRD_FRD_FRD,
	otawa_target_FNMADD_FRD_FRD_FRD_FRD,
	otawa_target_FMADDS__FRD_FRD_FRD_FRD,
	otawa_target_FMADDS_FRD_FRD_FRD_FRD,
	otawa_target_FMADD__FRD_FRD_FRD_FRD,
	otawa_target_FMADD_FRD_FRD_FRD_FRD,
	otawa_target_FDIVS__FRD_FRD_FRD,
	otawa_target_FDIVS_FRD_FRD_FRD,
	otawa_target_FDIV__FRD_FRD_FRD,
	otawa_target_FDIV_FRD_FRD_FRD,
	otawa_target_FMULS__FRD_FRD_FRD,
	otawa_target_FMULS_FRD_FRD_FRD,
	otawa_target_FMUL__FRD_FRD_FRD,
	otawa_target_FMUL_FRD_FRD_FRD,
	otawa_target_FSUBS__FRD_FRD_FRD,
	otawa_target_FSUBS_FRD_FRD_FRD,
	otawa_target_FSUB__FRD_FRD_FRD,
	otawa_target_FSUB_FRD_FRD_FRD,
	otawa_target_FADDS__FRD_FRD_FRD,
	otawa_target_FADDS_FRD_FRD_FRD,
	otawa_target_FADD__FRD_FRD_FRD,
	otawa_target_FADD_FRD_FRD_FRD,
	otawa_target_STFSUX_FRD_RD_RD,
	otawa_target_STFSU_FRD_D_LP_RD_RP_,
	otawa_target_STFSX_FRD_RD_RD,
	otawa_target_STFS_FRD_D_LP_RD_RP_,
	otawa_target_STFDUX_FRD_RD_RD,
	otawa_target_STFDU_FRD_D_LP_RD_RP_,
	otawa_target_STFDX_FRD_RD_RD,
	otawa_target_STFD_FRD_D_LP_RD_RP_,
	otawa_target_LFSUX_FRD_RD_RD,
	otawa_target_LFSU_FRD_D_LP_RD_RP_,
	otawa_target_LFSX_FRD_RD_RD,
	otawa_target_LFS_FRD_D_LP_RD_RP_,
	otawa_target_LFDUX_FRD_RD_RD,
	otawa_target_LFDU_FRD_D_LP_RD_RP_,
	otawa_target_LFDX_FRD_RD_RD,
	otawa_target_LFD_FRD_D_LP_RD_RP_,
	otawa_target_TWI_D_RD_D,
	otawa_target_TW_D_RD_RD_0,
	otawa_target_SYNC,
	otawa_target_STWCX__RD_RD_RD_0,
	otawa_target_LWARX_RD_RD_RD_0,
	otawa_target_MFSPR_RD_S_0,
	otawa_target_MTSPR_S_RD_0,
	otawa_target_MFCR_RD_0,
	otawa_target_ISEL_RD__RD__R5B__D_0,
	otawa_target_MCRXR_CRFD_0,
	otawa_target_MTCRF_D_RD_0,
	otawa_target_MCRF_CRFD_CRFD,
	otawa_target_CRORC_CRBD_CRBD_CRBD,
	otawa_target_CRANDC_CRBD_CRBD_CRBD,
	otawa_target_CREQV_CRBD_CRBD_CRBD,
	otawa_target_CRNOR_CRBD_CRBD_CRBD,
	otawa_target_CRNAND_CRBD_CRBD_CRBD,
	otawa_target_CRXOR_CRBD_CRBD_CRBD,
	otawa_target_CROR_CRBD_CRBD_CRBD,
	otawa_target_CRAND_CRBD_CRBD_CRBD,
	otawa_target_SRAW__RD_RD_RD_0,
	otawa_target_SRAW_RD_RD_RD_0,
	otawa_target_SRAWI__RD_RD_D_0,
	otawa_target_SRAWI_RD_RD_D_0,
	otawa_target_SRW__RD_RD_RD_0,
	otawa_target_SRW_RD_RD_RD_0,
	otawa_target_SLW__RD_RD_RD_0,
	otawa_target_SLW_RD_RD_RD_0,
	otawa_target_RLWIMI__RD_RD_D_D_D,
	otawa_target_RLWIMI_RD_RD_D_D_D,
	otawa_target_RLWNM__RD_RD_RD_D_D,
	otawa_target_RLWNM_RD_RD_RD_D_D,
	otawa_target_RLWINM__RD_RD_D_D_D,
	otawa_target_RLWINM_RD_RD_D_D_D,
	otawa_target_CNTLZW__RD__RD_0,
	otawa_target_CNTLZW_RD__RD_0,
	otawa_target_EXTSH__RD_RD_0,
	otawa_target_EXTSH_RD_RD_0,
	otawa_target_EXTSB__RD_RD_0,
	otawa_target_EXTSB_RD_RD_0,
	otawa_target_EQV__RD_RD_RD_0,
	otawa_target_EQV_RD_RD_RD_0,
	otawa_target_NAND__RD_RD_RD_0,
	otawa_target_NAND_RD_RD_RD_0,
	otawa_target_NOR__RD_RD_RD_0,
	otawa_target_NOR_RD_RD_RD_0,
	otawa_target_XORIS_RD_RD_D,
	otawa_target_XORI_RD_RD_D,
	otawa_target_XOR__RD_RD_RD_0,
	otawa_target_XOR_RD_RD_RD_0,
	otawa_target_ANDC__RD_RD_RD_0,
	otawa_target_ANDC_RD_RD_RD_0,
	otawa_target_ANDIS__RD_RD_D,
	otawa_target_ANDI__RD_RD_D,
	otawa_target_AND__RD_RD_RD_0,
	otawa_target_AND_RD_RD_RD_0,
	otawa_target_ORC__RD_RD_RD_0,
	otawa_target_ORC_RD_RD_RD_0,
	otawa_target_ORIS_RD_RD_D,
	otawa_target_ORI_RD_RD_D,
	otawa_target_OR__RD_RD_RD_0,
	otawa_target_OR_RD_RD_RD_0,
	otawa_target_CMPL_D_D_RD_RD_0,
	otawa_target_CMPLI_D_D_RD_D,
	otawa_target_CMP_D_D_RD_RD_0,
	otawa_target_CMPI_D_D_RD_D,
	otawa_target_NEGO__RD_RD_0,
	otawa_target_NEGO_RD_RD_0,
	otawa_target_NEG__RD_RD_0,
	otawa_target_NEG_RD_RD_0,
	otawa_target_DIVWUO__RD_RD_RD_0,
	otawa_target_DIVWUO_RD_RD_RD_0,
	otawa_target_DIVWU__RD_RD_RD_0,
	otawa_target_DIVWU_RD_RD_RD_0,
	otawa_target_DIVWO__RD_RD_RD_0,
	otawa_target_DIVWO_RD_RD_RD_0,
	otawa_target_DIVW__RD_RD_RD_0,
	otawa_target_DIVW_RD_RD_RD_0,
	otawa_target_MULHWU__RD_RD_RD_0,
	otawa_target_MULHWU_RD_RD_RD_0,
	otawa_target_MULHW__RD_RD_RD_0,
	otawa_target_MULHW_RD_RD_RD_0,
	otawa_target_MULLI_RD_RD_D,
	otawa_target_MULLWO__RD_RD_RD_0,
	otawa_target_MULLWO_RD_RD_RD_0,
	otawa_target_MULLW__RD_RD_RD_0,
	otawa_target_MULLW_RD_RD_RD_0,
	otawa_target_SUBFZEO__RD_RD_0,
	otawa_target_SUBFZEO_RD_RD_0,
	otawa_target_SUBFZE__RD_RD_0,
	otawa_target_SUBFZE_RD_RD_0,
	otawa_target_SUBFMEO__RD_RD_0,
	otawa_target_SUBFMEO_RD_RD_0,
	otawa_target_SUBFME__RD_RD_0,
	otawa_target_SUBFME_RD_RD_0,
	otawa_target_SUBFEO__RD_RD_RD_0,
	otawa_target_SUBFEO_RD_RD_RD_0,
	otawa_target_SUBFE__RD_RD_RD_0,
	otawa_target_SUBFE_RD_RD_RD_0,
	otawa_target_SUBFCO__RD_RD_RD_0,
	otawa_target_SUBFCO_RD_RD_RD_0,
	otawa_target_SUBFC__RD_RD_RD_0,
	otawa_target_SUBFC_RD_RD_RD_0,
	otawa_target_SUBFIC_RD_RD_D,
	otawa_target_SUBFO__RD_RD_RD_0,
	otawa_target_SUBFO_RD_RD_RD_0,
	otawa_target_SUBF__RD_RD_RD_0,
	otawa_target_SUBF_RD_RD_RD_0,
	otawa_target_ADDZEO__RD_RD_0,
	otawa_target_ADDZEO_RD_RD_0,
	otawa_target_ADDZE__RD_RD_0,
	otawa_target_ADDZE_RD_RD_0,
	otawa_target_ADDMEO__RD_RD_0,
	otawa_target_ADDMEO_RD_RD_0,
	otawa_target_ADDME__RD_RD_0,
	otawa_target_ADDME_RD_RD_0,
	otawa_target_ADDEO__RD_RD_RD_0,
	otawa_target_ADDEO_RD_RD_RD_0,
	otawa_target_ADDE__RD_RD_RD_0,
	otawa_target_ADDE_RD_RD_RD_0,
	otawa_target_ADDCO__RD_RD_RD_0,
	otawa_target_ADDCO_RD_RD_RD_0,
	otawa_target_ADDC__RD_RD_RD_0,
	otawa_target_ADDC_RD_RD_RD_0,
	otawa_target_ADDIC__RD_RD_D,
	otawa_target_ADDIC_RD_RD_D,
	otawa_target_ADDIS_RD_RD_D,
	otawa_target_ADDI_RD_RD_D,
	otawa_target_ADDSS_RD_RD_RD_0,
	otawa_target_STSWX_RD_RD_RD_0,
	otawa_target_STSWI_RD_RD_D_0,
	otawa_target_STMW_RD_D_LP_RD_RP_,
	otawa_target_STWBRX_RD_RD_RD_0,
	otawa_target_STHBRX_RD_RD_RD_0,
	otawa_target_STWUX_RD_RD_RD_0,
	otawa_target_STWU_RD_D_LP_RD_RP_,
	otawa_target_STWX_RD_RD_RD_0,
	otawa_target_STW_RD_D_LP_RD_RP_,
	otawa_target_STHUX_RD_RD_RD_0,
	otawa_target_STHU_RD_D_LP_RD_RP_,
	otawa_target_STHX_RD_RD_RD_0,
	otawa_target_STH_RD_D_LP_RD_RP_,
	otawa_target_STBUX_RD_RD_RD_0,
	otawa_target_STBU_RD_D_LP_RD_RP_,
	otawa_target_STBX_RD_RD_RD_0,
	otawa_target_STB_RD_D_LP_RD_RP_,
	otawa_target_LSWX_RD_RD_RD,
	otawa_target_LSWI_RD_RD_D,
	otawa_target_LMW_RD_D_LP_RD_RP_,
	otawa_target_LWBRX_RD_RD_RD_0,
	otawa_target_LHBRX_RD_RD_RD_0,
	otawa_target_LWZUX_RD_RD_RD_0,
	otawa_target_LWZU_RD_D_LP_RD_RP_,
	otawa_target_LWZX_RD_RD_RD_0,
	otawa_target_LWZ_RD_D_LP_RD_RP_,
	otawa_target_LHAUX_RD_RD_RD_0,
	otawa_target_LHAU_RD_D_LP_RD_RP_,
	otawa_target_LHAX_RD_RD_RD_0,
	otawa_target_LHA_RD_D_LP_RD_RP_,
	otawa_target_LHZUX_RD_RD_RD_0,
	otawa_target_LHZU_RD_D_LP_RD_RP_,
	otawa_target_LHZX_RD_RD_RD_0,
	otawa_target_LHZ_RD_D_LP_RD_RP_,
	otawa_target_LBZUX_RD_RD_RD_0,
	otawa_target_LBZU_RD_D_LP_RD_RP_,
	otawa_target_LBZX_RD_RD_RD_0,
	otawa_target_LBZ_RD_D_LP_RD_RP_,
	otawa_target_SC,
	otawa_target_BCLRL_D_D,
	otawa_target_BCLR_D_D,
	otawa_target_BCCTRL_D_D,
	otawa_target_BCCTR_D_D,
	otawa_target_BCLA_D_D_D,
	otawa_target_BCL_D_D_D,
	otawa_target_BCA_D_D_D,
	otawa_target_BC_D_D_D,
	otawa_target_BLA_D,
	otawa_target_BL_0X08X,
	otawa_target_BA_D,
	otawa_target_B_D
};



/**
 * Get the OTAWA target of the instruction.
 * @return OTAWA target.
 */
otawa_target_t ppc_target(ppc_inst_t *inst)
{
        return ppc_target_table[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif

