/* Generated by gliss-attr (117/07/07 16:19:41) copyright (c) 2009 IRIT - UPS */

#include <ppc/api.h>
#include <ppc/id.h>
#include <ppc/macros.h>
#include <ppc/grt.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef int (*pred_fun_t)(ppc_inst_t *inst);

/*** function definition ***/

static int otawa_pred_UNKNOWN(ppc_inst_t *inst) {
	return -1;
}

static int otawa_pred_WRTEE_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_WRTEE_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_TLBWE(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_TLBSYNC(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_TLBSX_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_TLBRE(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_TLBIVAX_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MSYNC(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTDCR_D__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFDCR__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MBAR_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ICBT_D__RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_XOR__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_XOR_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ICBI_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBZ_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBTST_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBT_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBST_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBI_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBF_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBA_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_TW_D_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFCR_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFZEO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFZEO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFZE__RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFZE_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFMEO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFMEO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFME__RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFME_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFEO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFEO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFE__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFE_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFCO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFCO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFC__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFC_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBF__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBF_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STWCX__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STWBRX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STSWI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STSWX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STHBRX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STWUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STWX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STHUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STHX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STBUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STBX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SRW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SRW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SRAWI__RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SRAWI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SRAW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SRAW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SLW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SLW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ORC__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ORC_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_OR__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_OR_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTSPR_D_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTMSR_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFSPR_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFMSR_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NOR__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NOR_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NEGO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NEGO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NEG__RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NEG_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NAND__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NAND_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULLWO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULLWO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULLW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULLW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULHWU__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULHWU_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULHW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULHW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTSPR_S_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MCRXR_CRFD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTCRF_D_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFSPR_RD_S(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LWARX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LWBRX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LWZUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LWZX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHZUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHZX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHBRX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHAUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHAX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LBZUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LBZX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ISEL_RD__RD__R5B__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EXTSH__RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EXTSH_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EXTSB__RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EXTSB_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EQV__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EQV_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVWUO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVWUO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVWU__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVWU_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVWO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVWO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CNTLZW__RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CNTLZW_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CMPL_D_D_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CMP_D_D_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ANDC__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ANDC_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_AND__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_AND_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDZEO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDZEO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDZE__RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDZE_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDMEO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDMEO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDME__RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDME_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDEO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDEO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDE__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDE_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDCO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDCO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDC__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDC_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDSS_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_XORIS_RD__RD__X(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_SUBFICS_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_STMW_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_STWU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_STW_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_STHU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_STH_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_STBU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_STB_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_SRWIS_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_SLWIS_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_RLWINM_RD__RD__D__D__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_RLWIMI_RD__RD__D__D__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_RLWIS_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_RLWS_RD__RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_ORIS_RD__RD__X(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_OR2IS_RD__X(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_OR2I_RD__X(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_MULL2I_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_MULLI_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_MCRF_CRD__CRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_LMW_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_LWZU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_LWZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_LIS_RD__X(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_LI_RD__X(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_LHZU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_LHZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_LHAU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_LHA_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_LBZU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_LBZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CRXOR_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CRORC_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CROR_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CRNOR_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CRNAND_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CREQV_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CRANDC_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CRAND_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CMPLI_CRD__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CMPL16I_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CMPI_CRD__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CMPHL16I_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CMPHL_CRD__RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CMPH16I_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CMPH_CRD__RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_CMP16I_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_BCS_X__X_08X(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_BS_08X(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_ADDICS_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_AND2IS__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_AND2I__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_ADDICS_RD__RD__D_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_ADDIS_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_ADD2IS_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_ADD2I__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_ADD16I_RD__RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_SUBIS_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_SUBF_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_SUB_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_STW_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_STH_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_STB_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_SRWI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_SRW_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_SRAWI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_SRAW_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_SLWI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_SLW_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_SC(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_RFI(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_RFDI(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_RFCI(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_OR_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_NOT_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_NEG_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_MULLW_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_MTLR_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_MTCTR_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_MTAR_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_MR_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_MFLR_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_MFCTR_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_MFAR_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_LI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_LWZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_LHZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_LBZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_EXTZH_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_EXTZB_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_EXTSH_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_EXTSB_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_CMPLI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_CMPL_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_CMPI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_CMPHL_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_CMPH_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_CMP_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_BTSTI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_BSETI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_BMSKI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_BLRS(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_BGENI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_BCTRS(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_BCLRI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_BC_X__X__08X(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_BS_08X(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_ANDC_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_ANDI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_E_ANDS_RD__RD_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_ADDI_RD__D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SE_ADD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFAPIDI_RD__RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_TLBSYNC_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_TLBIE_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_TLBIA(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_RFI(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTSRIN_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTSR_D_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFSRIN_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFSR_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTSPR_D_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTMSR_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFSPR_RD_D_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFMSR_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFTB_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ISYNC(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EIEIO(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ECOWX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ECIWX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ICBI_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBZ_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBTST_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBT_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBST_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBI_RD__RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBF_RD__RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DCBA_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTFSFI__CRFD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTFSFI_CRFD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTFSF__D_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTFSF_D_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTFSB1__CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTFSB1_CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTFSB0__CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTFSB0_CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFFS__FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFFS_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MCRFS_CRFD_CRFD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FCTIWZ__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FCTIWZ_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FCTIW__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FCTIW_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FRSP__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FRSP_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FNABS__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FNABS_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FABS__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FABS_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FNEG__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FNEG_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMR__FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMR_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FCMPU_CRFD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FCMPO_CRFD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FNMSUBS__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FNMSUBS_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FNMSUB__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FNMSUB_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMSUBS__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMSUBS_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMSUB__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMSUB_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FNMADDS__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FNMADDS_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FNMADD__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FNMADD_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMADDS__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMADDS_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMADD__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMADD_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FDIVS__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FDIVS_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FDIV__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FDIV_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMULS__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMULS_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMUL__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FMUL_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FSUBS__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FSUBS_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FSUB__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FSUB_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FADDS__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FADDS_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FADD__FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_FADD_FRD_FRD_FRD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STFSUX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STFSU_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STFSX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STFS_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STFDUX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STFDU_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STFDX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STFD_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LFSUX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LFSU_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LFSX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LFS_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LFDUX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LFDU_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LFDX_FRD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LFD_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_TWI_D_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_TW_D_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SYNC(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STWCX__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LWARX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFSPR_RD_S_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTSPR_S_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MFCR_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ISEL_RD__RD__R5B__D_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MCRXR_CRFD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MTCRF_D_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MCRF_CRFD_CRFD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CRORC_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CRANDC_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CREQV_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CRNOR_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CRNAND_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CRXOR_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CROR_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CRAND_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SRAW__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SRAW_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SRAWI__RD_RD_D_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SRAWI_RD_RD_D_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SRW__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SRW_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SLW__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SLW_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_RLWIMI__RD_RD_D_D_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_RLWIMI_RD_RD_D_D_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_RLWNM__RD_RD_RD_D_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_RLWNM_RD_RD_RD_D_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_RLWINM__RD_RD_D_D_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_RLWINM_RD_RD_D_D_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CNTLZW__RD__RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CNTLZW_RD__RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EXTSH__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EXTSH_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EXTSB__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EXTSB_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EQV__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_EQV_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NAND__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NAND_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NOR__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NOR_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_XORIS_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_XORI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_XOR__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_XOR_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ANDC__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ANDC_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ANDIS__RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ANDI__RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_AND__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_AND_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ORC__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ORC_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ORIS_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ORI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_OR__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_OR_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CMPL_D_D_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CMPLI_D_D_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CMP_D_D_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_CMPI_D_D_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NEGO__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NEGO_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NEG__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_NEG_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVWUO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVWUO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVWU__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVWU_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVWO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVWO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVW__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_DIVW_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULHWU__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULHWU_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULHW__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULHW_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULLI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULLWO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULLWO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULLW__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_MULLW_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFZEO__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFZEO_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFZE__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFZE_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFMEO__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFMEO_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFME__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFME_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFEO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFEO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFE__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFE_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFCO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFCO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFC__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFC_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFIC_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBFO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBF__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SUBF_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDZEO__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDZEO_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDZE__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDZE_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDMEO__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDMEO_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDME__RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDME_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDEO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDEO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDE__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDE_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDCO__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDCO_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDC__RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDC_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDIC__RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDIC_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDIS_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_ADDSS_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STSWX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STSWI_RD_RD_D_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STMW_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STWBRX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STHBRX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STWUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STWU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STWX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STW_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STHUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STHU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STHX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STH_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STBUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STBU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STBX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_STB_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LSWX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LSWI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LMW_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LWBRX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHBRX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LWZUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LWZU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LWZX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LWZ_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHAUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHAU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHAX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHA_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHZUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHZU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHZX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LHZ_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LBZUX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LBZU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LBZX_RD_RD_RD_0(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_LBZ_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_SC(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_BCLRL_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCLRL_D_D_x_x_x_BO, (4 - 0)) && ppc_bit8(PPC_BCLRL_D_D_x_x_x_BO, (4 - 2))))
		__gtmp_1 = -1;
	else {
		if(ppc_bit8(PPC_BCLRL_D_D_x_x_x_BO, (4 - 4)))
			__gtmp_0 = 1;
		else
			__gtmp_0 = 0;
		__gtmp_1 = __gtmp_0;
	}
	return __gtmp_1;

};

static int otawa_pred_BCLR_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCLR_D_D_x_x_x_BO, (4 - 0)) && ppc_bit8(PPC_BCLR_D_D_x_x_x_BO, (4 - 2))))
		__gtmp_1 = -1;
	else {
		if(ppc_bit8(PPC_BCLR_D_D_x_x_x_BO, (4 - 4)))
			__gtmp_0 = 1;
		else
			__gtmp_0 = 0;
		__gtmp_1 = __gtmp_0;
	}
	return __gtmp_1;

};

static int otawa_pred_BCCTRL_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCCTRL_D_D_x_x_x_BO, (4 - 0)) && ppc_bit8(PPC_BCCTRL_D_D_x_x_x_BO, (4 - 2))))
		__gtmp_1 = -1;
	else {
		if(ppc_bit8(PPC_BCCTRL_D_D_x_x_x_BO, (4 - 4)))
			__gtmp_0 = 1;
		else
			__gtmp_0 = 0;
		__gtmp_1 = __gtmp_0;
	}
	return __gtmp_1;

};

static int otawa_pred_BCCTR_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCCTR_D_D_x_x_x_BO, (4 - 0)) && ppc_bit8(PPC_BCCTR_D_D_x_x_x_BO, (4 - 2))))
		__gtmp_1 = -1;
	else {
		if(ppc_bit8(PPC_BCCTR_D_D_x_x_x_BO, (4 - 4)))
			__gtmp_0 = 1;
		else
			__gtmp_0 = 0;
		__gtmp_1 = __gtmp_0;
	}
	return __gtmp_1;

};

static int otawa_pred_BCLA_D_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCLA_D_D_D_x_x_x_BO, (4 - 0)) && ppc_bit8(PPC_BCLA_D_D_D_x_x_x_BO, (4 - 2))))
		__gtmp_1 = -1;
	else {
		if((ppc_bit16(PPC_BCLA_D_D_D_x_x_x_BD_n, 14) ^ ppc_bit8(PPC_BCLA_D_D_D_x_x_x_BO, (4 - 4))))
			__gtmp_0 = 1;
		else
			__gtmp_0 = 0;
		__gtmp_1 = __gtmp_0;
	}
	return __gtmp_1;

};

static int otawa_pred_BCL_D_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCL_D_D_D_x_x_x_BO, (4 - 0)) && ppc_bit8(PPC_BCL_D_D_D_x_x_x_BO, (4 - 2))))
		__gtmp_1 = -1;
	else {
		if((ppc_bit16(PPC_BCL_D_D_D_x_x_x_BD_n, 14) ^ ppc_bit8(PPC_BCL_D_D_D_x_x_x_BO, (4 - 4))))
			__gtmp_0 = 1;
		else
			__gtmp_0 = 0;
		__gtmp_1 = __gtmp_0;
	}
	return __gtmp_1;

};

static int otawa_pred_BCA_D_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCA_D_D_D_x_x_x_BO, (4 - 0)) && ppc_bit8(PPC_BCA_D_D_D_x_x_x_BO, (4 - 2))))
		__gtmp_1 = -1;
	else {
		if((ppc_bit16(PPC_BCA_D_D_D_x_x_x_BD_n, 14) ^ ppc_bit8(PPC_BCA_D_D_D_x_x_x_BO, (4 - 4))))
			__gtmp_0 = 1;
		else
			__gtmp_0 = 0;
		__gtmp_1 = __gtmp_0;
	}
	return __gtmp_1;

};

static int otawa_pred_BC_D_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BC_D_D_D_x_x_x_BO, (4 - 0)) && ppc_bit8(PPC_BC_D_D_D_x_x_x_BO, (4 - 2))))
		__gtmp_1 = -1;
	else {
		if((ppc_bit16(PPC_BC_D_D_D_x_x_x_BD_n, 14) ^ ppc_bit8(PPC_BC_D_D_D_x_x_x_BO, (4 - 4))))
			__gtmp_0 = 1;
		else
			__gtmp_0 = 0;
		__gtmp_1 = __gtmp_0;
	}
	return __gtmp_1;

};

static int otawa_pred_BLA_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_BL_0X08X(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_BA_D(ppc_inst_t *inst) {
return 0;
};

static int otawa_pred_B_D(ppc_inst_t *inst) {
return 0;
};




/*** function table ***/
static pred_fun_t pred_funs[] = {
	otawa_pred_UNKNOWN,
	otawa_pred_WRTEE_D,
	otawa_pred_WRTEE_RD,
	otawa_pred_TLBWE,
	otawa_pred_TLBSYNC,
	otawa_pred_TLBSX_RD__RD,
	otawa_pred_TLBRE,
	otawa_pred_TLBIVAX_RD__RD,
	otawa_pred_MSYNC,
	otawa_pred_MTDCR_D__RD,
	otawa_pred_MFDCR__RD__D,
	otawa_pred_MBAR_D,
	otawa_pred_ICBT_D__RD__RD,
	otawa_pred_XOR__RD_RD_RD,
	otawa_pred_XOR_RD_RD_RD,
	otawa_pred_ICBI_RD_RD,
	otawa_pred_DCBZ_RD_RD,
	otawa_pred_DCBTST_RD_RD,
	otawa_pred_DCBT_RD_RD,
	otawa_pred_DCBST_RD_RD,
	otawa_pred_DCBI_RD__RD,
	otawa_pred_DCBF_RD__RD,
	otawa_pred_DCBA_RD_RD,
	otawa_pred_TW_D_RD_RD,
	otawa_pred_MFCR_RD,
	otawa_pred_SUBFZEO__RD_RD,
	otawa_pred_SUBFZEO_RD_RD,
	otawa_pred_SUBFZE__RD_RD,
	otawa_pred_SUBFZE_RD_RD,
	otawa_pred_SUBFMEO__RD_RD,
	otawa_pred_SUBFMEO_RD_RD,
	otawa_pred_SUBFME__RD_RD,
	otawa_pred_SUBFME_RD_RD,
	otawa_pred_SUBFEO__RD_RD_RD,
	otawa_pred_SUBFEO_RD_RD_RD,
	otawa_pred_SUBFE__RD_RD_RD,
	otawa_pred_SUBFE_RD_RD_RD,
	otawa_pred_SUBFCO__RD_RD_RD,
	otawa_pred_SUBFCO_RD_RD_RD,
	otawa_pred_SUBFC__RD_RD_RD,
	otawa_pred_SUBFC_RD_RD_RD,
	otawa_pred_SUBFO__RD_RD_RD,
	otawa_pred_SUBFO_RD_RD_RD,
	otawa_pred_SUBF__RD_RD_RD,
	otawa_pred_SUBF_RD_RD_RD,
	otawa_pred_STWCX__RD_RD_RD,
	otawa_pred_STWBRX_RD_RD_RD,
	otawa_pred_STSWI_RD_RD_D,
	otawa_pred_STSWX_RD_RD_RD,
	otawa_pred_STHBRX_RD_RD_RD,
	otawa_pred_STWUX_RD_RD_RD,
	otawa_pred_STWX_RD_RD_RD,
	otawa_pred_STHUX_RD_RD_RD,
	otawa_pred_STHX_RD_RD_RD,
	otawa_pred_STBUX_RD_RD_RD,
	otawa_pred_STBX_RD_RD_RD,
	otawa_pred_SRW__RD_RD_RD,
	otawa_pred_SRW_RD_RD_RD,
	otawa_pred_SRAWI__RD_RD_D,
	otawa_pred_SRAWI_RD_RD_D,
	otawa_pred_SRAW__RD_RD_RD,
	otawa_pred_SRAW_RD_RD_RD,
	otawa_pred_SLW__RD_RD_RD,
	otawa_pred_SLW_RD_RD_RD,
	otawa_pred_ORC__RD_RD_RD,
	otawa_pred_ORC_RD_RD_RD,
	otawa_pred_OR__RD_RD_RD,
	otawa_pred_OR_RD_RD_RD,
	otawa_pred_MTSPR_D_RD,
	otawa_pred_MTMSR_RD,
	otawa_pred_MFSPR_RD_D,
	otawa_pred_MFMSR_RD,
	otawa_pred_NOR__RD_RD_RD,
	otawa_pred_NOR_RD_RD_RD,
	otawa_pred_NEGO__RD_RD,
	otawa_pred_NEGO_RD_RD,
	otawa_pred_NEG__RD_RD,
	otawa_pred_NEG_RD_RD,
	otawa_pred_NAND__RD_RD_RD,
	otawa_pred_NAND_RD_RD_RD,
	otawa_pred_MULLWO__RD_RD_RD,
	otawa_pred_MULLWO_RD_RD_RD,
	otawa_pred_MULLW__RD_RD_RD,
	otawa_pred_MULLW_RD_RD_RD,
	otawa_pred_MULHWU__RD_RD_RD,
	otawa_pred_MULHWU_RD_RD_RD,
	otawa_pred_MULHW__RD_RD_RD,
	otawa_pred_MULHW_RD_RD_RD,
	otawa_pred_MTSPR_S_RD,
	otawa_pred_MCRXR_CRFD,
	otawa_pred_MTCRF_D_RD,
	otawa_pred_MFSPR_RD_S,
	otawa_pred_LWARX_RD_RD_RD,
	otawa_pred_LWBRX_RD_RD_RD,
	otawa_pred_LWZUX_RD_RD_RD,
	otawa_pred_LWZX_RD_RD_RD,
	otawa_pred_LHZUX_RD_RD_RD,
	otawa_pred_LHZX_RD_RD_RD,
	otawa_pred_LHBRX_RD_RD_RD,
	otawa_pred_LHAUX_RD_RD_RD,
	otawa_pred_LHAX_RD_RD_RD,
	otawa_pred_LBZUX_RD_RD_RD,
	otawa_pred_LBZX_RD_RD_RD,
	otawa_pred_ISEL_RD__RD__R5B__D,
	otawa_pred_EXTSH__RD_RD,
	otawa_pred_EXTSH_RD_RD,
	otawa_pred_EXTSB__RD_RD,
	otawa_pred_EXTSB_RD_RD,
	otawa_pred_EQV__RD_RD_RD,
	otawa_pred_EQV_RD_RD_RD,
	otawa_pred_DIVWUO__RD_RD_RD,
	otawa_pred_DIVWUO_RD_RD_RD,
	otawa_pred_DIVWU__RD_RD_RD,
	otawa_pred_DIVWU_RD_RD_RD,
	otawa_pred_DIVWO__RD_RD_RD,
	otawa_pred_DIVWO_RD_RD_RD,
	otawa_pred_DIVW__RD_RD_RD,
	otawa_pred_DIVW_RD_RD_RD,
	otawa_pred_CNTLZW__RD__RD,
	otawa_pred_CNTLZW_RD__RD,
	otawa_pred_CMPL_D_D_RD_RD,
	otawa_pred_CMP_D_D_RD_RD,
	otawa_pred_ANDC__RD_RD_RD,
	otawa_pred_ANDC_RD_RD_RD,
	otawa_pred_AND__RD_RD_RD,
	otawa_pred_AND_RD_RD_RD,
	otawa_pred_ADDZEO__RD_RD,
	otawa_pred_ADDZEO_RD_RD,
	otawa_pred_ADDZE__RD_RD,
	otawa_pred_ADDZE_RD_RD,
	otawa_pred_ADDMEO__RD_RD,
	otawa_pred_ADDMEO_RD_RD,
	otawa_pred_ADDME__RD_RD,
	otawa_pred_ADDME_RD_RD,
	otawa_pred_ADDEO__RD_RD_RD,
	otawa_pred_ADDEO_RD_RD_RD,
	otawa_pred_ADDE__RD_RD_RD,
	otawa_pred_ADDE_RD_RD_RD,
	otawa_pred_ADDCO__RD_RD_RD,
	otawa_pred_ADDCO_RD_RD_RD,
	otawa_pred_ADDC__RD_RD_RD,
	otawa_pred_ADDC_RD_RD_RD,
	otawa_pred_ADDSS_RD_RD_RD,
	otawa_pred_E_XORIS_RD__RD__X,
	otawa_pred_E_SUBFICS_RD__RD__D,
	otawa_pred_E_STMW_RD__D_LP_RD_RP_,
	otawa_pred_E_STWU_RD__D_LP_RD_RP_,
	otawa_pred_E_STW_RD__D_LP_RD_RP_,
	otawa_pred_E_STHU_RD__D_LP_RD_RP_,
	otawa_pred_E_STH_RD__D_LP_RD_RP_,
	otawa_pred_E_STBU_RD__D_LP_RD_RP_,
	otawa_pred_E_STB_RD__D_LP_RD_RP_,
	otawa_pred_E_SRWIS_RD__RD__D,
	otawa_pred_E_SLWIS_RD__RD__D,
	otawa_pred_E_RLWINM_RD__RD__D__D__D,
	otawa_pred_E_RLWIMI_RD__RD__D__D__D,
	otawa_pred_E_RLWIS_RD__RD__D,
	otawa_pred_E_RLWS_RD__RD__RD,
	otawa_pred_E_ORIS_RD__RD__X,
	otawa_pred_E_OR2IS_RD__X,
	otawa_pred_E_OR2I_RD__X,
	otawa_pred_E_MULL2I_RD__D,
	otawa_pred_E_MULLI_RD__RD__D,
	otawa_pred_E_MCRF_CRD__CRD,
	otawa_pred_E_LMW_RD__D_LP_RD_RP_,
	otawa_pred_E_LWZU_RD__D_LP_RD_RP_,
	otawa_pred_E_LWZ_RD__D_LP_RD_RP_,
	otawa_pred_E_LIS_RD__X,
	otawa_pred_E_LI_RD__X,
	otawa_pred_E_LHZU_RD__D_LP_RD_RP_,
	otawa_pred_E_LHZ_RD__D_LP_RD_RP_,
	otawa_pred_E_LHAU_RD__D_LP_RD_RP_,
	otawa_pred_E_LHA_RD__D_LP_RD_RP_,
	otawa_pred_E_LBZU_RD__D_LP_RD_RP_,
	otawa_pred_E_LBZ_RD__D_LP_RD_RP_,
	otawa_pred_E_CRXOR_CRBD__CRBD__CRBD,
	otawa_pred_E_CRORC_CRBD__CRBD__CRBD,
	otawa_pred_E_CROR_CRBD__CRBD__CRBD,
	otawa_pred_E_CRNOR_CRBD__CRBD__CRBD,
	otawa_pred_E_CRNAND_CRBD__CRBD__CRBD,
	otawa_pred_E_CREQV_CRBD__CRBD__CRBD,
	otawa_pred_E_CRANDC_CRBD__CRBD__CRBD,
	otawa_pred_E_CRAND_CRBD__CRBD__CRBD,
	otawa_pred_E_CMPLI_CRD__RD__D,
	otawa_pred_E_CMPL16I_RD__D,
	otawa_pred_E_CMPI_CRD__RD__D,
	otawa_pred_E_CMPHL16I_RD__D,
	otawa_pred_E_CMPHL_CRD__RD__RD,
	otawa_pred_E_CMPH16I_RD__D,
	otawa_pred_E_CMPH_CRD__RD__RD,
	otawa_pred_E_CMP16I_RD__D,
	otawa_pred_E_BCS_X__X_08X,
	otawa_pred_E_BS_08X,
	otawa_pred_E_ADDICS_RD__RD__D,
	otawa_pred_E_AND2IS__RD__D,
	otawa_pred_E_AND2I__RD__D,
	otawa_pred_E_ADDICS_RD__RD__D_0,
	otawa_pred_E_ADDIS_RD__RD__D,
	otawa_pred_E_ADD2IS_RD__D,
	otawa_pred_E_ADD2I__RD__D,
	otawa_pred_E_ADD16I_RD__RD__D,
	otawa_pred_SE_SUBIS_RD__D,
	otawa_pred_SE_SUBF_RD__RD,
	otawa_pred_SE_SUB_RD__RD,
	otawa_pred_SE_STW_RD__D_LP_RD_RP_,
	otawa_pred_SE_STH_RD__D_LP_RD_RP_,
	otawa_pred_SE_STB_RD__D_LP_RD_RP_,
	otawa_pred_SE_SRWI_RD__D,
	otawa_pred_SE_SRW_RD__RD,
	otawa_pred_SE_SRAWI_RD__D,
	otawa_pred_SE_SRAW_RD__RD,
	otawa_pred_SE_SLWI_RD__D,
	otawa_pred_SE_SLW_RD__RD,
	otawa_pred_SE_SC,
	otawa_pred_SE_RFI,
	otawa_pred_SE_RFDI,
	otawa_pred_SE_RFCI,
	otawa_pred_SE_OR_RD__RD,
	otawa_pred_SE_NOT_RD,
	otawa_pred_SE_NEG_RD,
	otawa_pred_SE_MULLW_RD__RD,
	otawa_pred_SE_MTLR_RD,
	otawa_pred_SE_MTCTR_RD,
	otawa_pred_SE_MTAR_RD__RD,
	otawa_pred_SE_MR_RD__RD,
	otawa_pred_SE_MFLR_RD,
	otawa_pred_SE_MFCTR_RD,
	otawa_pred_SE_MFAR_RD__RD,
	otawa_pred_SE_LI_RD__D,
	otawa_pred_SE_LWZ_RD__D_LP_RD_RP_,
	otawa_pred_SE_LHZ_RD__D_LP_RD_RP_,
	otawa_pred_SE_LBZ_RD__D_LP_RD_RP_,
	otawa_pred_SE_EXTZH_RD,
	otawa_pred_SE_EXTZB_RD,
	otawa_pred_SE_EXTSH_RD,
	otawa_pred_SE_EXTSB_RD,
	otawa_pred_SE_CMPLI_RD__D,
	otawa_pred_SE_CMPL_RD__RD,
	otawa_pred_SE_CMPI_RD__D,
	otawa_pred_SE_CMPHL_RD__RD,
	otawa_pred_SE_CMPH_RD__RD,
	otawa_pred_SE_CMP_RD__RD,
	otawa_pred_SE_BTSTI_RD__D,
	otawa_pred_SE_BSETI_RD__D,
	otawa_pred_SE_BMSKI_RD__D,
	otawa_pred_BLRS,
	otawa_pred_BGENI_RD__D,
	otawa_pred_SE_BCTRS,
	otawa_pred_BCLRI_RD__D,
	otawa_pred_SE_BC_X__X__08X,
	otawa_pred_SE_BS_08X,
	otawa_pred_SE_ANDC_RD__RD,
	otawa_pred_SE_ANDI_RD__D,
	otawa_pred_E_ANDS_RD__RD_,
	otawa_pred_SE_ADDI_RD__D,
	otawa_pred_SE_ADD_RD_RD,
	otawa_pred_MFAPIDI_RD__RD,
	otawa_pred_TLBSYNC_0,
	otawa_pred_TLBIE_RD,
	otawa_pred_TLBIA,
	otawa_pred_RFI,
	otawa_pred_MTSRIN_RD_RD,
	otawa_pred_MTSR_D_RD,
	otawa_pred_MFSRIN_RD_RD,
	otawa_pred_MFSR_RD_D,
	otawa_pred_MTSPR_D_RD_0,
	otawa_pred_MTMSR_RD_0,
	otawa_pred_MFSPR_RD_D_0,
	otawa_pred_MFMSR_RD_0,
	otawa_pred_MFTB_RD_D,
	otawa_pred_ISYNC,
	otawa_pred_EIEIO,
	otawa_pred_ECOWX_RD_RD_RD,
	otawa_pred_ECIWX_RD_RD_RD,
	otawa_pred_ICBI_RD_RD_0,
	otawa_pred_DCBZ_RD_RD_0,
	otawa_pred_DCBTST_RD_RD_0,
	otawa_pred_DCBT_RD_RD_0,
	otawa_pred_DCBST_RD_RD_0,
	otawa_pred_DCBI_RD__RD_0,
	otawa_pred_DCBF_RD__RD_0,
	otawa_pred_DCBA_RD_RD_0,
	otawa_pred_MTFSFI__CRFD_D,
	otawa_pred_MTFSFI_CRFD_D,
	otawa_pred_MTFSF__D_FRD,
	otawa_pred_MTFSF_D_FRD,
	otawa_pred_MTFSB1__CRBD,
	otawa_pred_MTFSB1_CRBD,
	otawa_pred_MTFSB0__CRBD,
	otawa_pred_MTFSB0_CRBD,
	otawa_pred_MFFS__FRD,
	otawa_pred_MFFS_FRD,
	otawa_pred_MCRFS_CRFD_CRFD,
	otawa_pred_FCTIWZ__FRD_FRD,
	otawa_pred_FCTIWZ_FRD_FRD,
	otawa_pred_FCTIW__FRD_FRD,
	otawa_pred_FCTIW_FRD_FRD,
	otawa_pred_FRSP__FRD_FRD,
	otawa_pred_FRSP_FRD_FRD,
	otawa_pred_FNABS__FRD_FRD,
	otawa_pred_FNABS_FRD_FRD,
	otawa_pred_FABS__FRD_FRD,
	otawa_pred_FABS_FRD_FRD,
	otawa_pred_FNEG__FRD_FRD,
	otawa_pred_FNEG_FRD_FRD,
	otawa_pred_FMR__FRD_FRD,
	otawa_pred_FMR_FRD_FRD,
	otawa_pred_FCMPU_CRFD_FRD_FRD,
	otawa_pred_FCMPO_CRFD_FRD_FRD,
	otawa_pred_FNMSUBS__FRD_FRD_FRD_FRD,
	otawa_pred_FNMSUBS_FRD_FRD_FRD_FRD,
	otawa_pred_FNMSUB__FRD_FRD_FRD_FRD,
	otawa_pred_FNMSUB_FRD_FRD_FRD_FRD,
	otawa_pred_FMSUBS__FRD_FRD_FRD_FRD,
	otawa_pred_FMSUBS_FRD_FRD_FRD_FRD,
	otawa_pred_FMSUB__FRD_FRD_FRD_FRD,
	otawa_pred_FMSUB_FRD_FRD_FRD_FRD,
	otawa_pred_FNMADDS__FRD_FRD_FRD_FRD,
	otawa_pred_FNMADDS_FRD_FRD_FRD_FRD,
	otawa_pred_FNMADD__FRD_FRD_FRD_FRD,
	otawa_pred_FNMADD_FRD_FRD_FRD_FRD,
	otawa_pred_FMADDS__FRD_FRD_FRD_FRD,
	otawa_pred_FMADDS_FRD_FRD_FRD_FRD,
	otawa_pred_FMADD__FRD_FRD_FRD_FRD,
	otawa_pred_FMADD_FRD_FRD_FRD_FRD,
	otawa_pred_FDIVS__FRD_FRD_FRD,
	otawa_pred_FDIVS_FRD_FRD_FRD,
	otawa_pred_FDIV__FRD_FRD_FRD,
	otawa_pred_FDIV_FRD_FRD_FRD,
	otawa_pred_FMULS__FRD_FRD_FRD,
	otawa_pred_FMULS_FRD_FRD_FRD,
	otawa_pred_FMUL__FRD_FRD_FRD,
	otawa_pred_FMUL_FRD_FRD_FRD,
	otawa_pred_FSUBS__FRD_FRD_FRD,
	otawa_pred_FSUBS_FRD_FRD_FRD,
	otawa_pred_FSUB__FRD_FRD_FRD,
	otawa_pred_FSUB_FRD_FRD_FRD,
	otawa_pred_FADDS__FRD_FRD_FRD,
	otawa_pred_FADDS_FRD_FRD_FRD,
	otawa_pred_FADD__FRD_FRD_FRD,
	otawa_pred_FADD_FRD_FRD_FRD,
	otawa_pred_STFSUX_FRD_RD_RD,
	otawa_pred_STFSU_FRD_D_LP_RD_RP_,
	otawa_pred_STFSX_FRD_RD_RD,
	otawa_pred_STFS_FRD_D_LP_RD_RP_,
	otawa_pred_STFDUX_FRD_RD_RD,
	otawa_pred_STFDU_FRD_D_LP_RD_RP_,
	otawa_pred_STFDX_FRD_RD_RD,
	otawa_pred_STFD_FRD_D_LP_RD_RP_,
	otawa_pred_LFSUX_FRD_RD_RD,
	otawa_pred_LFSU_FRD_D_LP_RD_RP_,
	otawa_pred_LFSX_FRD_RD_RD,
	otawa_pred_LFS_FRD_D_LP_RD_RP_,
	otawa_pred_LFDUX_FRD_RD_RD,
	otawa_pred_LFDU_FRD_D_LP_RD_RP_,
	otawa_pred_LFDX_FRD_RD_RD,
	otawa_pred_LFD_FRD_D_LP_RD_RP_,
	otawa_pred_TWI_D_RD_D,
	otawa_pred_TW_D_RD_RD_0,
	otawa_pred_SYNC,
	otawa_pred_STWCX__RD_RD_RD_0,
	otawa_pred_LWARX_RD_RD_RD_0,
	otawa_pred_MFSPR_RD_S_0,
	otawa_pred_MTSPR_S_RD_0,
	otawa_pred_MFCR_RD_0,
	otawa_pred_ISEL_RD__RD__R5B__D_0,
	otawa_pred_MCRXR_CRFD_0,
	otawa_pred_MTCRF_D_RD_0,
	otawa_pred_MCRF_CRFD_CRFD,
	otawa_pred_CRORC_CRBD_CRBD_CRBD,
	otawa_pred_CRANDC_CRBD_CRBD_CRBD,
	otawa_pred_CREQV_CRBD_CRBD_CRBD,
	otawa_pred_CRNOR_CRBD_CRBD_CRBD,
	otawa_pred_CRNAND_CRBD_CRBD_CRBD,
	otawa_pred_CRXOR_CRBD_CRBD_CRBD,
	otawa_pred_CROR_CRBD_CRBD_CRBD,
	otawa_pred_CRAND_CRBD_CRBD_CRBD,
	otawa_pred_SRAW__RD_RD_RD_0,
	otawa_pred_SRAW_RD_RD_RD_0,
	otawa_pred_SRAWI__RD_RD_D_0,
	otawa_pred_SRAWI_RD_RD_D_0,
	otawa_pred_SRW__RD_RD_RD_0,
	otawa_pred_SRW_RD_RD_RD_0,
	otawa_pred_SLW__RD_RD_RD_0,
	otawa_pred_SLW_RD_RD_RD_0,
	otawa_pred_RLWIMI__RD_RD_D_D_D,
	otawa_pred_RLWIMI_RD_RD_D_D_D,
	otawa_pred_RLWNM__RD_RD_RD_D_D,
	otawa_pred_RLWNM_RD_RD_RD_D_D,
	otawa_pred_RLWINM__RD_RD_D_D_D,
	otawa_pred_RLWINM_RD_RD_D_D_D,
	otawa_pred_CNTLZW__RD__RD_0,
	otawa_pred_CNTLZW_RD__RD_0,
	otawa_pred_EXTSH__RD_RD_0,
	otawa_pred_EXTSH_RD_RD_0,
	otawa_pred_EXTSB__RD_RD_0,
	otawa_pred_EXTSB_RD_RD_0,
	otawa_pred_EQV__RD_RD_RD_0,
	otawa_pred_EQV_RD_RD_RD_0,
	otawa_pred_NAND__RD_RD_RD_0,
	otawa_pred_NAND_RD_RD_RD_0,
	otawa_pred_NOR__RD_RD_RD_0,
	otawa_pred_NOR_RD_RD_RD_0,
	otawa_pred_XORIS_RD_RD_D,
	otawa_pred_XORI_RD_RD_D,
	otawa_pred_XOR__RD_RD_RD_0,
	otawa_pred_XOR_RD_RD_RD_0,
	otawa_pred_ANDC__RD_RD_RD_0,
	otawa_pred_ANDC_RD_RD_RD_0,
	otawa_pred_ANDIS__RD_RD_D,
	otawa_pred_ANDI__RD_RD_D,
	otawa_pred_AND__RD_RD_RD_0,
	otawa_pred_AND_RD_RD_RD_0,
	otawa_pred_ORC__RD_RD_RD_0,
	otawa_pred_ORC_RD_RD_RD_0,
	otawa_pred_ORIS_RD_RD_D,
	otawa_pred_ORI_RD_RD_D,
	otawa_pred_OR__RD_RD_RD_0,
	otawa_pred_OR_RD_RD_RD_0,
	otawa_pred_CMPL_D_D_RD_RD_0,
	otawa_pred_CMPLI_D_D_RD_D,
	otawa_pred_CMP_D_D_RD_RD_0,
	otawa_pred_CMPI_D_D_RD_D,
	otawa_pred_NEGO__RD_RD_0,
	otawa_pred_NEGO_RD_RD_0,
	otawa_pred_NEG__RD_RD_0,
	otawa_pred_NEG_RD_RD_0,
	otawa_pred_DIVWUO__RD_RD_RD_0,
	otawa_pred_DIVWUO_RD_RD_RD_0,
	otawa_pred_DIVWU__RD_RD_RD_0,
	otawa_pred_DIVWU_RD_RD_RD_0,
	otawa_pred_DIVWO__RD_RD_RD_0,
	otawa_pred_DIVWO_RD_RD_RD_0,
	otawa_pred_DIVW__RD_RD_RD_0,
	otawa_pred_DIVW_RD_RD_RD_0,
	otawa_pred_MULHWU__RD_RD_RD_0,
	otawa_pred_MULHWU_RD_RD_RD_0,
	otawa_pred_MULHW__RD_RD_RD_0,
	otawa_pred_MULHW_RD_RD_RD_0,
	otawa_pred_MULLI_RD_RD_D,
	otawa_pred_MULLWO__RD_RD_RD_0,
	otawa_pred_MULLWO_RD_RD_RD_0,
	otawa_pred_MULLW__RD_RD_RD_0,
	otawa_pred_MULLW_RD_RD_RD_0,
	otawa_pred_SUBFZEO__RD_RD_0,
	otawa_pred_SUBFZEO_RD_RD_0,
	otawa_pred_SUBFZE__RD_RD_0,
	otawa_pred_SUBFZE_RD_RD_0,
	otawa_pred_SUBFMEO__RD_RD_0,
	otawa_pred_SUBFMEO_RD_RD_0,
	otawa_pred_SUBFME__RD_RD_0,
	otawa_pred_SUBFME_RD_RD_0,
	otawa_pred_SUBFEO__RD_RD_RD_0,
	otawa_pred_SUBFEO_RD_RD_RD_0,
	otawa_pred_SUBFE__RD_RD_RD_0,
	otawa_pred_SUBFE_RD_RD_RD_0,
	otawa_pred_SUBFCO__RD_RD_RD_0,
	otawa_pred_SUBFCO_RD_RD_RD_0,
	otawa_pred_SUBFC__RD_RD_RD_0,
	otawa_pred_SUBFC_RD_RD_RD_0,
	otawa_pred_SUBFIC_RD_RD_D,
	otawa_pred_SUBFO__RD_RD_RD_0,
	otawa_pred_SUBFO_RD_RD_RD_0,
	otawa_pred_SUBF__RD_RD_RD_0,
	otawa_pred_SUBF_RD_RD_RD_0,
	otawa_pred_ADDZEO__RD_RD_0,
	otawa_pred_ADDZEO_RD_RD_0,
	otawa_pred_ADDZE__RD_RD_0,
	otawa_pred_ADDZE_RD_RD_0,
	otawa_pred_ADDMEO__RD_RD_0,
	otawa_pred_ADDMEO_RD_RD_0,
	otawa_pred_ADDME__RD_RD_0,
	otawa_pred_ADDME_RD_RD_0,
	otawa_pred_ADDEO__RD_RD_RD_0,
	otawa_pred_ADDEO_RD_RD_RD_0,
	otawa_pred_ADDE__RD_RD_RD_0,
	otawa_pred_ADDE_RD_RD_RD_0,
	otawa_pred_ADDCO__RD_RD_RD_0,
	otawa_pred_ADDCO_RD_RD_RD_0,
	otawa_pred_ADDC__RD_RD_RD_0,
	otawa_pred_ADDC_RD_RD_RD_0,
	otawa_pred_ADDIC__RD_RD_D,
	otawa_pred_ADDIC_RD_RD_D,
	otawa_pred_ADDIS_RD_RD_D,
	otawa_pred_ADDI_RD_RD_D,
	otawa_pred_ADDSS_RD_RD_RD_0,
	otawa_pred_STSWX_RD_RD_RD_0,
	otawa_pred_STSWI_RD_RD_D_0,
	otawa_pred_STMW_RD_D_LP_RD_RP_,
	otawa_pred_STWBRX_RD_RD_RD_0,
	otawa_pred_STHBRX_RD_RD_RD_0,
	otawa_pred_STWUX_RD_RD_RD_0,
	otawa_pred_STWU_RD_D_LP_RD_RP_,
	otawa_pred_STWX_RD_RD_RD_0,
	otawa_pred_STW_RD_D_LP_RD_RP_,
	otawa_pred_STHUX_RD_RD_RD_0,
	otawa_pred_STHU_RD_D_LP_RD_RP_,
	otawa_pred_STHX_RD_RD_RD_0,
	otawa_pred_STH_RD_D_LP_RD_RP_,
	otawa_pred_STBUX_RD_RD_RD_0,
	otawa_pred_STBU_RD_D_LP_RD_RP_,
	otawa_pred_STBX_RD_RD_RD_0,
	otawa_pred_STB_RD_D_LP_RD_RP_,
	otawa_pred_LSWX_RD_RD_RD,
	otawa_pred_LSWI_RD_RD_D,
	otawa_pred_LMW_RD_D_LP_RD_RP_,
	otawa_pred_LWBRX_RD_RD_RD_0,
	otawa_pred_LHBRX_RD_RD_RD_0,
	otawa_pred_LWZUX_RD_RD_RD_0,
	otawa_pred_LWZU_RD_D_LP_RD_RP_,
	otawa_pred_LWZX_RD_RD_RD_0,
	otawa_pred_LWZ_RD_D_LP_RD_RP_,
	otawa_pred_LHAUX_RD_RD_RD_0,
	otawa_pred_LHAU_RD_D_LP_RD_RP_,
	otawa_pred_LHAX_RD_RD_RD_0,
	otawa_pred_LHA_RD_D_LP_RD_RP_,
	otawa_pred_LHZUX_RD_RD_RD_0,
	otawa_pred_LHZU_RD_D_LP_RD_RP_,
	otawa_pred_LHZX_RD_RD_RD_0,
	otawa_pred_LHZ_RD_D_LP_RD_RP_,
	otawa_pred_LBZUX_RD_RD_RD_0,
	otawa_pred_LBZU_RD_D_LP_RD_RP_,
	otawa_pred_LBZX_RD_RD_RD_0,
	otawa_pred_LBZ_RD_D_LP_RD_RP_,
	otawa_pred_SC,
	otawa_pred_BCLRL_D_D,
	otawa_pred_BCLR_D_D,
	otawa_pred_BCCTRL_D_D,
	otawa_pred_BCCTR_D_D,
	otawa_pred_BCLA_D_D_D,
	otawa_pred_BCL_D_D_D,
	otawa_pred_BCA_D_D_D,
	otawa_pred_BC_D_D_D,
	otawa_pred_BLA_D,
	otawa_pred_BL_0X08X,
	otawa_pred_BA_D,
	otawa_pred_B_D
};

/**
 * Get the OTAWA static prediction of the instruction.
 * @return OTAWA static prediction.
 */
int ppc_pred(ppc_inst_t *inst) {
	return pred_funs[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif
