/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

extern "C" {
#include <$(proc)/api.h>
#include <$(proc)/id.h>
#include <$(proc)/macros.h>
#include <$(proc)/grt.h>
}

typedef void (*sem_fun_t)($(proc)_inst_t *inst, otawa::sem::Block& block);

/*** functions ***/

static void otawa_sem_UNKNOWN($(proc)_inst_t *inst, otawa::sem::Block& block) {
}

$(foreach instructions)
static void otawa_sem_$(IDENT)($(proc)_inst_t *inst, otawa::sem::Block& block) {
$(otawa_sem)
};

$(end)


/*** function table ***/
static sem_fun_t sem_funs[] = {
	otawa_sem_UNKNOWN$(foreach instructions),
	otawa_sem_$(IDENT)$(end)
};

/**
 * Get the OTAWA semantics of the instruction.
 * @param inst		Current GLISS instruction.
 * @param block		Block to write semantic instructions in.
 */
static void $(proc)_sem($(proc)_inst_t *inst, otawa::sem::Block& block) {
	sem_funs[inst->ident](inst, block);
}
