# CMake generated Testfile for 
# Source directory: /cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/tools
# Build directory: /cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/tools
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(simple-file-bs.arm "gel-file" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/bs.arm")
add_test(simple-file-crc-stabs.elf "gel-file" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/crc-stabs.elf")
add_test(simple-file-fibcall.ppc "gel-file" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/fibcall.ppc")
add_test(simple-file-empty.ppc "gel-file" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/empty.ppc")
add_test(simple-line-bs.arm "gel-line" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/bs.arm")
add_test(simple-line-crc-stabs.elf "gel-line" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/crc-stabs.elf")
add_test(simple-line-fibcall.ppc "gel-line" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/fibcall.ppc")
add_test(simple-line-empty.ppc "gel-line" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/empty.ppc")
add_test(simple-prog-bs.arm "gel-prog" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/bs.arm")
add_test(simple-prog-crc-stabs.elf "gel-prog" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/crc-stabs.elf")
add_test(simple-prog-fibcall.ppc "gel-prog" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/fibcall.ppc")
add_test(simple-prog-empty.ppc "gel-prog" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/empty.ppc")
add_test(simple-sect-bs.arm "gel-sect" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/bs.arm")
add_test(simple-sect-crc-stabs.elf "gel-sect" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/crc-stabs.elf")
add_test(simple-sect-fibcall.ppc "gel-sect" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/fibcall.ppc")
add_test(simple-sect-empty.ppc "gel-sect" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/empty.ppc")
add_test(simple-sym-bs.arm "gel-sym" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/bs.arm")
add_test(simple-sym-crc-stabs.elf "gel-sym" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/crc-stabs.elf")
add_test(simple-sym-fibcall.ppc "gel-sym" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/fibcall.ppc")
add_test(simple-sym-empty.ppc "gel-sym" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/empty.ppc")
add_test(simple-im-bs.arm "gel-im" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/bs.arm")
add_test(simple-im-crc-stabs.elf "gel-im" "/cygdrive/d/Seafile/Workspace/MyProject/WCET/WCET/otawa/gel/test/bin/crc-stabs.elf")
add_test(diff-file-bs.arm "cmake" ".." "-DDIFF_TOOL=file" "-DDIFF_INPUT=bs.arm")
add_test(diff-file-crc-stabs.elf "cmake" ".." "-DDIFF_TOOL=file" "-DDIFF_INPUT=crc-stabs.elf")
add_test(diff-file-fibcall.ppc "cmake" ".." "-DDIFF_TOOL=file" "-DDIFF_INPUT=fibcall.ppc")
add_test(diff-file-empty.ppc "cmake" ".." "-DDIFF_TOOL=file" "-DDIFF_INPUT=empty.ppc")
add_test(diff-line-bs.arm "cmake" ".." "-DDIFF_TOOL=line" "-DDIFF_INPUT=bs.arm")
add_test(diff-line-crc-stabs.elf "cmake" ".." "-DDIFF_TOOL=line" "-DDIFF_INPUT=crc-stabs.elf")
add_test(diff-line-fibcall.ppc "cmake" ".." "-DDIFF_TOOL=line" "-DDIFF_INPUT=fibcall.ppc")
add_test(diff-line-empty.ppc "cmake" ".." "-DDIFF_TOOL=line" "-DDIFF_INPUT=empty.ppc")
add_test(diff-prog-bs.arm "cmake" ".." "-DDIFF_TOOL=prog" "-DDIFF_INPUT=bs.arm")
add_test(diff-prog-crc-stabs.elf "cmake" ".." "-DDIFF_TOOL=prog" "-DDIFF_INPUT=crc-stabs.elf")
add_test(diff-prog-fibcall.ppc "cmake" ".." "-DDIFF_TOOL=prog" "-DDIFF_INPUT=fibcall.ppc")
add_test(diff-prog-empty.ppc "cmake" ".." "-DDIFF_TOOL=prog" "-DDIFF_INPUT=empty.ppc")
add_test(diff-sect-bs.arm "cmake" ".." "-DDIFF_TOOL=sect" "-DDIFF_INPUT=bs.arm")
add_test(diff-sect-crc-stabs.elf "cmake" ".." "-DDIFF_TOOL=sect" "-DDIFF_INPUT=crc-stabs.elf")
add_test(diff-sect-fibcall.ppc "cmake" ".." "-DDIFF_TOOL=sect" "-DDIFF_INPUT=fibcall.ppc")
add_test(diff-sect-empty.ppc "cmake" ".." "-DDIFF_TOOL=sect" "-DDIFF_INPUT=empty.ppc")
add_test(diff-sym-bs.arm "cmake" ".." "-DDIFF_TOOL=sym" "-DDIFF_INPUT=bs.arm")
add_test(diff-sym-crc-stabs.elf "cmake" ".." "-DDIFF_TOOL=sym" "-DDIFF_INPUT=crc-stabs.elf")
add_test(diff-sym-fibcall.ppc "cmake" ".." "-DDIFF_TOOL=sym" "-DDIFF_INPUT=fibcall.ppc")
add_test(diff-sym-empty.ppc "cmake" ".." "-DDIFF_TOOL=sym" "-DDIFF_INPUT=empty.ppc")
add_test(diff-im-bs.arm "cmake" ".." "-DDIFF_TOOL=im" "-DDIFF_INPUT=bs.arm")
add_test(diff-im-crc-stabs.elf "cmake" ".." "-DDIFF_TOOL=im" "-DDIFF_INPUT=crc-stabs.elf")
