/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#include <stdlib.h>
#include <stdio.h>
#include <ppc/fetch.h>
#include <ppc/decode.h> /* api.h will be in it, for fetch functions, decode_table.h also */
#include <ppc/config.h> /* for memory endiannesses */
#include <ppc/code.h>

#include "code_table.h"


/**
 * Execute the given instruction in the given state.
 * @param state		Current execution state.
 * @param inst		Current instruction to execute.
 */
void ppc_execute(ppc_state_t *state, ppc_inst_t *inst)
{
	ppc_code_table[inst->ident](state, inst);
}


/* End of file ppc_code.c */
