/* Generated by GLISS V2.0 Copyright (c) 2009 IRIT - UPS (117/07/07 15:08:27) */
#ifndef PPC_PLATFORM_H
#define PPC_PLATFORM_H

#include <ppc/api.h>
#include <ppc/mem.h>
#include <ppc/grt.h>
#include <ppc/error.h>
#include <ppc/gen_int.h>
#include <ppc/loader.h>
#include <ppc/syscall.h>
#include <ppc/sysparm.h>
#include <ppc/code.h>
#include <ppc/exception.h>
#include <ppc/fpi.h>
#include <ppc/env.h>
#include <ppc/vea.h>


/* ppc_platform_t structure */
struct ppc_platform_t
{
	int usage;

	/* entry point of the simulated program */
	ppc_address_t entry;
	/* initial sp, argv, envp ... */
	ppc_env_t *sys_env;

	union
	{
		ppc_memory_t *array[0];
		struct
		{
			ppc_memory_t *M;

		} named;
	} mems;
	PPC_MEM_STATE
	PPC_GRT_STATE
	PPC_ERROR_STATE
	PPC_GEN_INT_STATE
	PPC_LOADER_STATE
	PPC_SYSCALL_STATE
	PPC_SYSPARM_STATE
	PPC_CODE_STATE
	PPC_EXCEPTION_STATE
	PPC_FPI_STATE
	PPC_ENV_STATE
	PPC_VEA_STATE

};

/* functions */

#endif	/* PPC_PLATFORM_H */
