/* Generated by gliss-attr (117/07/07 16:19:40) copyright (c) 2009 IRIT - UPS */

#include <ppc/api.h>
#include <ppc/id.h>
#include <ppc/macros.h>
#include <ppc/grt.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef unsigned long otawa_kind_t;
typedef otawa_kind_t (*fun_t)(ppc_inst_t *inst);

/*** function definition ***/

static otawa_kind_t otawa_kind_UNKNOWN(ppc_inst_t *inst) {
	return 0;
}

static otawa_kind_t otawa_kind_WRTEE_D(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_WRTEE_RD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_TLBWE(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_TLBSYNC(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_TLBSX_RD__RD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_TLBRE(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_TLBIVAX_RD__RD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MSYNC(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MTDCR_D__RD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MFDCR__RD__D(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MBAR_D(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_ICBT_D__RD__RD(ppc_inst_t *inst) {
	return ((16 | 32) | 16384LU);

};

static otawa_kind_t otawa_kind_XOR__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_XOR_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ICBI_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DCBZ_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DCBTST_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DCBT_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DCBST_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DCBI_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DCBF_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DCBA_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_TW_D_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MFCR_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFZEO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFZEO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFZE__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFZE_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFMEO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFMEO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFME__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFME_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFEO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFEO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFE__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFE_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFCO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFCO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFC__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFC_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBFO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBF__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBF_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STWCX__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STWBRX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STSWI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STSWX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STHBRX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STWUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STWX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STHUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STHX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STBUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STBX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SRW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SRW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SRAWI__RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SRAWI_RD_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SRAW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SRAW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SLW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SLW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ORC__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ORC_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_OR__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_OR_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MTSPR_D_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MTMSR_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MFSPR_RD_D(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MFMSR_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_NOR__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_NOR_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_NEGO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_NEGO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_NEG__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_NEG_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_NAND__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_NAND_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MULLWO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MULLWO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MULLW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MULLW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MULHWU__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MULHWU_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MULHW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MULHW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MTSPR_S_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MCRXR_CRFD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MTCRF_D_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MFSPR_RD_S(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LWARX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LWBRX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LWZUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LWZX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LHZUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LHZX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LHBRX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LHAUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LHAX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LBZUX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LBZX_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ISEL_RD__RD__R5B__D(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_EXTSH__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_EXTSH_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_EXTSB__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_EXTSB_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_EQV__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_EQV_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DIVWUO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DIVWUO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DIVWU__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DIVWU_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DIVWO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DIVWO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DIVW__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_DIVW_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CNTLZW__RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CNTLZW_RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CMPL_D_D_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CMP_D_D_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ANDC__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ANDC_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_AND__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_AND_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDZEO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDZEO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDZE__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDZE_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDMEO__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDMEO_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDME__RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDME_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDEO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDEO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDE__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDE_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDCO__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDCO_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDC__RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDC_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDSS_RD_RD_RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_E_XORIS_RD__RD__X(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_SUBFICS_RD__RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_STMW_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return (((16 | 64) | 32768LU) | 128);

};

static otawa_kind_t otawa_kind_E_STWU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_E_STW_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_E_STHU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_E_STH_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_E_STBU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_E_STB_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_E_SRWIS_RD__RD__D(ppc_inst_t *inst) {
	return ((512LU | 128) | 4096LU);

};

static otawa_kind_t otawa_kind_E_SLWIS_RD__RD__D(ppc_inst_t *inst) {
	return ((512LU | 128) | 4096LU);

};

static otawa_kind_t otawa_kind_E_RLWINM_RD__RD__D__D__D(ppc_inst_t *inst) {
	return ((512LU | 128) | 4096LU);

};

static otawa_kind_t otawa_kind_E_RLWIMI_RD__RD__D__D__D(ppc_inst_t *inst) {
	return ((512LU | 128) | 4096LU);

};

static otawa_kind_t otawa_kind_E_RLWIS_RD__RD__D(ppc_inst_t *inst) {
	return ((512LU | 128) | 4096LU);

};

static otawa_kind_t otawa_kind_E_RLWS_RD__RD__RD(ppc_inst_t *inst) {
	return ((512LU | 128) | 4096LU);

};

static otawa_kind_t otawa_kind_E_ORIS_RD__RD__X(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_OR2IS_RD__X(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_OR2I_RD__X(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_MULL2I_RD__D(ppc_inst_t *inst) {
	return ((512LU | 128) | 1024LU);

};

static otawa_kind_t otawa_kind_E_MULLI_RD__RD__D(ppc_inst_t *inst) {
	return ((512LU | 128) | 1024LU);

};

static otawa_kind_t otawa_kind_E_MCRF_CRD__CRD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_E_LMW_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return (((16 | 32) | 32768LU) | 128);

};

static otawa_kind_t otawa_kind_E_LWZU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_E_LWZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_E_LIS_RD__X(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_LI_RD__X(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_LHZU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_E_LHZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_E_LHAU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_E_LHA_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_E_LBZU_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_E_LBZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_E_CRXOR_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_E_CRORC_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_E_CROR_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_E_CRNOR_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_E_CRNAND_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_E_CREQV_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_E_CRANDC_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_E_CRAND_CRBD__CRBD__CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_E_CMPLI_CRD__RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_CMPL16I_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_CMPI_CRD__RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_CMPHL16I_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_CMPHL_CRD__RD__RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_CMPH16I_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_CMPH_CRD__RD__RD(ppc_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_E_CMP16I_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_BCS_X__X_08X(ppc_inst_t *inst) {
	uint32_t __gtmp_0;
	if(PPC_E_BCS_X__X_08X_x_x_LK)
		__gtmp_0 = 4;
	else
		__gtmp_0 = 0;
	return ((2 | 1) | __gtmp_0);

};

static otawa_kind_t otawa_kind_E_BS_08X(ppc_inst_t *inst) {
	uint32_t __gtmp_0;
	if(PPC_E_BS_08X_x_x_LK)
		__gtmp_0 = 4;
	else
		__gtmp_0 = 0;
	return (2 | __gtmp_0);

};

static otawa_kind_t otawa_kind_E_ADDICS_RD__RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_AND2IS__RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_AND2I__RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_ADDICS_RD__RD__D_0(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_ADDIS_RD__RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_ADD2IS_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_ADD2I__RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_ADD16I_RD__RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_SUBIS_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_SUBF_RD__RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_SUB_RD__RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_STW_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_SE_STH_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_SE_STB_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 64) | 128);

};

static otawa_kind_t otawa_kind_SE_SRWI_RD__D(ppc_inst_t *inst) {
	return ((512LU | 128) | 4096LU);

};

static otawa_kind_t otawa_kind_SE_SRW_RD__RD(ppc_inst_t *inst) {
	return ((512LU | 128) | 4096LU);

};

static otawa_kind_t otawa_kind_SE_SRAWI_RD__D(ppc_inst_t *inst) {
	return ((512LU | 128) | 4096LU);

};

static otawa_kind_t otawa_kind_SE_SRAW_RD__RD(ppc_inst_t *inst) {
	return ((512LU | 128) | 4096LU);

};

static otawa_kind_t otawa_kind_SE_SLWI_RD__D(ppc_inst_t *inst) {
	return ((512LU | 128) | 4096LU);

};

static otawa_kind_t otawa_kind_SE_SLW_RD__RD(ppc_inst_t *inst) {
	return ((512LU | 128) | 4096LU);

};

static otawa_kind_t otawa_kind_SE_SC(ppc_inst_t *inst) {
	return ((2 | 4) | 16384LU);

};

static otawa_kind_t otawa_kind_SE_RFI(ppc_inst_t *inst) {
	return ((2 | 8) | 16384LU);

};

static otawa_kind_t otawa_kind_SE_RFDI(ppc_inst_t *inst) {
	return ((2 | 8) | 16384LU);

};

static otawa_kind_t otawa_kind_SE_RFCI(ppc_inst_t *inst) {
	return ((2 | 8) | 16384LU);

};

static otawa_kind_t otawa_kind_SE_OR_RD__RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_NOT_RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_NEG_RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_MULLW_RD__RD(ppc_inst_t *inst) {
	return (128 | 1024LU);

};

static otawa_kind_t otawa_kind_SE_MTLR_RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_MTCTR_RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_MTAR_RD__RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_MR_RD__RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_MFLR_RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_MFCTR_RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_MFAR_RD__RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_LI_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_LWZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_SE_LHZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_SE_LBZ_RD__D_LP_RD_RP_(ppc_inst_t *inst) {
	return ((16 | 32) | 128);

};

static otawa_kind_t otawa_kind_SE_EXTZH_RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_EXTZB_RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_EXTSH_RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_EXTSB_RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_CMPLI_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_CMPL_RD__RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_CMPI_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_CMPHL_RD__RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_CMPH_RD__RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_CMP_RD__RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_BTSTI_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_BSETI_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_BMSKI_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_BLRS(ppc_inst_t *inst) {
	return (2 | 8);

};

static otawa_kind_t otawa_kind_BGENI_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_BCTRS(ppc_inst_t *inst) {
	uint32_t __gtmp_0;
	if(PPC_SE_BCTRS_x_x_LK)
		__gtmp_0 = 4;
	else
		__gtmp_0 = 0;
	return (2 | __gtmp_0);

};

static otawa_kind_t otawa_kind_BCLRI_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_BC_X__X__08X(ppc_inst_t *inst) {
	return (2 | 1);

};

static otawa_kind_t otawa_kind_SE_BS_08X(ppc_inst_t *inst) {
	uint32_t __gtmp_0;
	if(PPC_SE_BS_08X_x_x_LK)
		__gtmp_0 = 4;
	else
		__gtmp_0 = 0;
	return (2 | __gtmp_0);

};

static otawa_kind_t otawa_kind_SE_ANDC_RD__RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_ANDI_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_E_ANDS_RD__RD_(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_ADDI_RD__D(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_SE_ADD_RD_RD(ppc_inst_t *inst) {
	return (512LU | 128);

};

static otawa_kind_t otawa_kind_MFAPIDI_RD__RD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_TLBSYNC_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_TLBIE_RD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_TLBIA(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_RFI(ppc_inst_t *inst) {
	return 8194LU;

};

static otawa_kind_t otawa_kind_MTSRIN_RD_RD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MTSR_D_RD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MFSRIN_RD_RD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MFSR_RD_D(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MTSPR_D_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MTMSR_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MFSPR_RD_D_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MFMSR_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MFTB_RD_D(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_ISYNC(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_EIEIO(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_ECOWX_RD_RD_RD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_ECIWX_RD_RD_RD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_ICBI_RD_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_DCBZ_RD_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_DCBTST_RD_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_DCBT_RD_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_DCBST_RD_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_DCBI_RD__RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_DCBF_RD__RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_DCBA_RD_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MTFSFI__CRFD_D(ppc_inst_t *inst) {
	return 16640LU;

};

static otawa_kind_t otawa_kind_MTFSFI_CRFD_D(ppc_inst_t *inst) {
	return 16640LU;

};

static otawa_kind_t otawa_kind_MTFSF__D_FRD(ppc_inst_t *inst) {
	return 16640LU;

};

static otawa_kind_t otawa_kind_MTFSF_D_FRD(ppc_inst_t *inst) {
	return 16640LU;

};

static otawa_kind_t otawa_kind_MTFSB1__CRBD(ppc_inst_t *inst) {
	return 16640LU;

};

static otawa_kind_t otawa_kind_MTFSB1_CRBD(ppc_inst_t *inst) {
	return 16640LU;

};

static otawa_kind_t otawa_kind_MTFSB0__CRBD(ppc_inst_t *inst) {
	return 16640LU;

};

static otawa_kind_t otawa_kind_MTFSB0_CRBD(ppc_inst_t *inst) {
	return 16640LU;

};

static otawa_kind_t otawa_kind_MFFS__FRD(ppc_inst_t *inst) {
	return 16640LU;

};

static otawa_kind_t otawa_kind_MFFS_FRD(ppc_inst_t *inst) {
	return 16640LU;

};

static otawa_kind_t otawa_kind_MCRFS_CRFD_CRFD(ppc_inst_t *inst) {
	return 16640LU;

};

static otawa_kind_t otawa_kind_FCTIWZ__FRD_FRD(ppc_inst_t *inst) {
	return 896LU;

};

static otawa_kind_t otawa_kind_FCTIWZ_FRD_FRD(ppc_inst_t *inst) {
	return 896LU;

};

static otawa_kind_t otawa_kind_FCTIW__FRD_FRD(ppc_inst_t *inst) {
	return 896LU;

};

static otawa_kind_t otawa_kind_FCTIW_FRD_FRD(ppc_inst_t *inst) {
	return 896LU;

};

static otawa_kind_t otawa_kind_FRSP__FRD_FRD(ppc_inst_t *inst) {
	return 896LU;

};

static otawa_kind_t otawa_kind_FRSP_FRD_FRD(ppc_inst_t *inst) {
	return 896LU;

};

static otawa_kind_t otawa_kind_FNABS__FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FNABS_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FABS__FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FABS_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FNEG__FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FNEG_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FMR__FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FMR_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FCMPU_CRFD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FCMPO_CRFD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FNMSUBS__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FNMSUBS_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FNMSUB__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FNMSUB_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FMSUBS__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FMSUBS_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FMSUB__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FMSUB_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FNMADDS__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FNMADDS_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FNMADD__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FNMADD_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FMADDS__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FMADDS_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FMADD__FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FMADD_FRD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FDIVS__FRD_FRD_FRD(ppc_inst_t *inst) {
	return 2816LU;

};

static otawa_kind_t otawa_kind_FDIVS_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 2816LU;

};

static otawa_kind_t otawa_kind_FDIV__FRD_FRD_FRD(ppc_inst_t *inst) {
	return 2816LU;

};

static otawa_kind_t otawa_kind_FDIV_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 2816LU;

};

static otawa_kind_t otawa_kind_FMULS__FRD_FRD_FRD(ppc_inst_t *inst) {
	return 1792LU;

};

static otawa_kind_t otawa_kind_FMULS_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 1792LU;

};

static otawa_kind_t otawa_kind_FMUL__FRD_FRD_FRD(ppc_inst_t *inst) {
	return 1792LU;

};

static otawa_kind_t otawa_kind_FMUL_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 1792LU;

};

static otawa_kind_t otawa_kind_FSUBS__FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FSUBS_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FSUB__FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FSUB_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FADDS__FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FADDS_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FADD__FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_FADD_FRD_FRD_FRD(ppc_inst_t *inst) {
	return 768LU;

};

static otawa_kind_t otawa_kind_STFSUX_FRD_RD_RD(ppc_inst_t *inst) {
	return 336LU;

};

static otawa_kind_t otawa_kind_STFSU_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 336LU;

};

static otawa_kind_t otawa_kind_STFSX_FRD_RD_RD(ppc_inst_t *inst) {
	return 336LU;

};

static otawa_kind_t otawa_kind_STFS_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 336LU;

};

static otawa_kind_t otawa_kind_STFDUX_FRD_RD_RD(ppc_inst_t *inst) {
	return 336LU;

};

static otawa_kind_t otawa_kind_STFDU_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 336LU;

};

static otawa_kind_t otawa_kind_STFDX_FRD_RD_RD(ppc_inst_t *inst) {
	return 336LU;

};

static otawa_kind_t otawa_kind_STFD_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 336LU;

};

static otawa_kind_t otawa_kind_LFSUX_FRD_RD_RD(ppc_inst_t *inst) {
	return 304LU;

};

static otawa_kind_t otawa_kind_LFSU_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 304LU;

};

static otawa_kind_t otawa_kind_LFSX_FRD_RD_RD(ppc_inst_t *inst) {
	return 304LU;

};

static otawa_kind_t otawa_kind_LFS_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 304LU;

};

static otawa_kind_t otawa_kind_LFDUX_FRD_RD_RD(ppc_inst_t *inst) {
	return 304LU;

};

static otawa_kind_t otawa_kind_LFDU_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 304LU;

};

static otawa_kind_t otawa_kind_LFDX_FRD_RD_RD(ppc_inst_t *inst) {
	return 304LU;

};

static otawa_kind_t otawa_kind_LFD_FRD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 304LU;

};

static otawa_kind_t otawa_kind_TWI_D_RD_D(ppc_inst_t *inst) {
	return 8194LU;

};

static otawa_kind_t otawa_kind_TW_D_RD_RD_0(ppc_inst_t *inst) {
	return 8194LU;

};

static otawa_kind_t otawa_kind_SYNC(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_STWCX__RD_RD_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_LWARX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MFSPR_RD_S_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MTSPR_S_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MFCR_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_ISEL_RD__RD__R5B__D_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MCRXR_CRFD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MTCRF_D_RD_0(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_MCRF_CRFD_CRFD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_CRORC_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_CRANDC_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_CREQV_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_CRNOR_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_CRNAND_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_CRXOR_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_CROR_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_CRAND_CRBD_CRBD_CRBD(ppc_inst_t *inst) {
	return 16384LU;

};

static otawa_kind_t otawa_kind_SRAW__RD_RD_RD_0(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_SRAW_RD_RD_RD_0(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_SRAWI__RD_RD_D_0(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_SRAWI_RD_RD_D_0(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_SRW__RD_RD_RD_0(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_SRW_RD_RD_RD_0(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_SLW__RD_RD_RD_0(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_SLW_RD_RD_RD_0(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_RLWIMI__RD_RD_D_D_D(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_RLWIMI_RD_RD_D_D_D(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_RLWNM__RD_RD_RD_D_D(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_RLWNM_RD_RD_RD_D_D(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_RLWINM__RD_RD_D_D_D(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_RLWINM_RD_RD_D_D_D(ppc_inst_t *inst) {
	return 4736LU;

};

static otawa_kind_t otawa_kind_CNTLZW__RD__RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_CNTLZW_RD__RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_EXTSH__RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_EXTSH_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_EXTSB__RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_EXTSB_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_EQV__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_EQV_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_NAND__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_NAND_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_NOR__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_NOR_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_XORIS_RD_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_XORI_RD_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_XOR__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_XOR_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ANDC__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ANDC_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ANDIS__RD_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ANDI__RD_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_AND__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_AND_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ORC__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ORC_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ORIS_RD_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ORI_RD_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_OR__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_OR_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_CMPL_D_D_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_CMPLI_D_D_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_CMP_D_D_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_CMPI_D_D_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_NEGO__RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_NEGO_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_NEG__RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_NEG_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_DIVWUO__RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 2048LU);

};

static otawa_kind_t otawa_kind_DIVWUO_RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 2048LU);

};

static otawa_kind_t otawa_kind_DIVWU__RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 2048LU);

};

static otawa_kind_t otawa_kind_DIVWU_RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 2048LU);

};

static otawa_kind_t otawa_kind_DIVWO__RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 2048LU);

};

static otawa_kind_t otawa_kind_DIVWO_RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 2048LU);

};

static otawa_kind_t otawa_kind_DIVW__RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 2048LU);

};

static otawa_kind_t otawa_kind_DIVW_RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 2048LU);

};

static otawa_kind_t otawa_kind_MULHWU__RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 1024LU);

};

static otawa_kind_t otawa_kind_MULHWU_RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 1024LU);

};

static otawa_kind_t otawa_kind_MULHW__RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 1024LU);

};

static otawa_kind_t otawa_kind_MULHW_RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 1024LU);

};

static otawa_kind_t otawa_kind_MULLI_RD_RD_D(ppc_inst_t *inst) {
	return (640LU | 1024LU);

};

static otawa_kind_t otawa_kind_MULLWO__RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 1024LU);

};

static otawa_kind_t otawa_kind_MULLWO_RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 1024LU);

};

static otawa_kind_t otawa_kind_MULLW__RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 1024LU);

};

static otawa_kind_t otawa_kind_MULLW_RD_RD_RD_0(ppc_inst_t *inst) {
	return (640LU | 1024LU);

};

static otawa_kind_t otawa_kind_SUBFZEO__RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFZEO_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFZE__RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFZE_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFMEO__RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFMEO_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFME__RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFME_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFEO__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFEO_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFE__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFE_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFCO__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFCO_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFC__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFC_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFIC_RD_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFO__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBFO_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBF__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_SUBF_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDZEO__RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDZEO_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDZE__RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDZE_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDMEO__RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDMEO_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDME__RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDME_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDEO__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDEO_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDE__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDE_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDCO__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDCO_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDC__RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDC_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDIC__RD_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDIC_RD_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDIS_RD_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDI_RD_RD_D(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_ADDSS_RD_RD_RD_0(ppc_inst_t *inst) {
	return 640LU;

};

static otawa_kind_t otawa_kind_STSWX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STSWI_RD_RD_D_0(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STMW_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STWBRX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STHBRX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STWUX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STWU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STWX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STW_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STHUX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STHU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STHX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STH_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STBUX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STBU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STBX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_STB_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 208;

};

static otawa_kind_t otawa_kind_LSWX_RD_RD_RD(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LSWI_RD_RD_D(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LMW_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LWBRX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LHBRX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LWZUX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LWZU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LWZX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LWZ_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LHAUX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LHAU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LHAX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LHA_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LHZUX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LHZU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LHZX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LHZ_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LBZUX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LBZU_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LBZX_RD_RD_RD_0(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_LBZ_RD_D_LP_RD_RP_(ppc_inst_t *inst) {
	return 176;

};

static otawa_kind_t otawa_kind_SC(ppc_inst_t *inst) {
	return 8194LU;

};

static otawa_kind_t otawa_kind_BCLRL_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCLRL_D_D_x_x_x_BO, 2) & ppc_bit8(PPC_BCLRL_D_D_x_x_x_BO, 4)))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	return (2 | ((4 | 2) | __gtmp_0));

};

static otawa_kind_t otawa_kind_BCLR_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCLR_D_D_x_x_x_BO, 2) & ppc_bit8(PPC_BCLR_D_D_x_x_x_BO, 4)))
		__gtmp_0 = (2 | 8);
	else
		__gtmp_0 = ((2 | 8) | 1);
	return (2 | __gtmp_0);

};

static otawa_kind_t otawa_kind_BCCTRL_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCCTRL_D_D_x_x_x_BO, 2) & ppc_bit8(PPC_BCCTRL_D_D_x_x_x_BO, 4)))
		__gtmp_0 = (2 | 4);
	else
		__gtmp_0 = ((2 | 4) | 1);
	return (2 | __gtmp_0);

};

static otawa_kind_t otawa_kind_BCCTR_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCCTR_D_D_x_x_x_BO, 2) & ppc_bit8(PPC_BCCTR_D_D_x_x_x_BO, 4)))
		__gtmp_0 = 2;
	else
		__gtmp_0 = (2 | 1);
	return (2 | __gtmp_0);

};

static otawa_kind_t otawa_kind_BCLA_D_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCLA_D_D_D_x_x_x_BO, 2) & ppc_bit8(PPC_BCLA_D_D_D_x_x_x_BO, 4)))
		__gtmp_0 = (2 | 4);
	else
		__gtmp_0 = ((2 | 4) | 1);
	return (2 | __gtmp_0);

};

static otawa_kind_t otawa_kind_BCL_D_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((PPC_BCL_D_D_D_x_x_x_BD_n == 1))
		__gtmp_1 = (512LU | 128);
	else {
		if((ppc_bit8(PPC_BCL_D_D_D_x_x_x_BO, 2) & ppc_bit8(PPC_BCL_D_D_D_x_x_x_BO, 4)))
			__gtmp_0 = (2 | 4);
		else
			__gtmp_0 = ((2 | 4) | 1);
		__gtmp_1 = __gtmp_0;
	}
	return (2 | __gtmp_1);

};

static otawa_kind_t otawa_kind_BCA_D_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BCA_D_D_D_x_x_x_BO, 2) & ppc_bit8(PPC_BCA_D_D_D_x_x_x_BO, 4)))
		__gtmp_0 = 2;
	else
		__gtmp_0 = (2 | 1);
	return (2 | __gtmp_0);

};

static otawa_kind_t otawa_kind_BC_D_D_D(ppc_inst_t *inst) {
	uint32_t __gtmp_0;
	if((ppc_bit8(PPC_BC_D_D_D_x_x_x_BO, 2) & ppc_bit8(PPC_BC_D_D_D_x_x_x_BO, 4)))
		__gtmp_0 = 2;
	else
		__gtmp_0 = (2 | 1);
	return (2 | __gtmp_0);

};

static otawa_kind_t otawa_kind_BLA_D(ppc_inst_t *inst) {
	return (2 | (2 | 4));

};

static otawa_kind_t otawa_kind_BL_0X08X(ppc_inst_t *inst) {
	uint32_t __gtmp_0;
	if((PPC_BL_0X08X_x_x_BRANCH_ADDR_n == 1))
		__gtmp_0 = (512LU | 128);
	else
		__gtmp_0 = (2 | 4);
	return (2 | __gtmp_0);

};

static otawa_kind_t otawa_kind_BA_D(ppc_inst_t *inst) {
	return (2 | 2);

};

static otawa_kind_t otawa_kind_B_D(ppc_inst_t *inst) {
	return (2 | 2);

};




/*** function table ***/
static fun_t kind_funs[] = {
	otawa_kind_UNKNOWN,
	otawa_kind_WRTEE_D,
	otawa_kind_WRTEE_RD,
	otawa_kind_TLBWE,
	otawa_kind_TLBSYNC,
	otawa_kind_TLBSX_RD__RD,
	otawa_kind_TLBRE,
	otawa_kind_TLBIVAX_RD__RD,
	otawa_kind_MSYNC,
	otawa_kind_MTDCR_D__RD,
	otawa_kind_MFDCR__RD__D,
	otawa_kind_MBAR_D,
	otawa_kind_ICBT_D__RD__RD,
	otawa_kind_XOR__RD_RD_RD,
	otawa_kind_XOR_RD_RD_RD,
	otawa_kind_ICBI_RD_RD,
	otawa_kind_DCBZ_RD_RD,
	otawa_kind_DCBTST_RD_RD,
	otawa_kind_DCBT_RD_RD,
	otawa_kind_DCBST_RD_RD,
	otawa_kind_DCBI_RD__RD,
	otawa_kind_DCBF_RD__RD,
	otawa_kind_DCBA_RD_RD,
	otawa_kind_TW_D_RD_RD,
	otawa_kind_MFCR_RD,
	otawa_kind_SUBFZEO__RD_RD,
	otawa_kind_SUBFZEO_RD_RD,
	otawa_kind_SUBFZE__RD_RD,
	otawa_kind_SUBFZE_RD_RD,
	otawa_kind_SUBFMEO__RD_RD,
	otawa_kind_SUBFMEO_RD_RD,
	otawa_kind_SUBFME__RD_RD,
	otawa_kind_SUBFME_RD_RD,
	otawa_kind_SUBFEO__RD_RD_RD,
	otawa_kind_SUBFEO_RD_RD_RD,
	otawa_kind_SUBFE__RD_RD_RD,
	otawa_kind_SUBFE_RD_RD_RD,
	otawa_kind_SUBFCO__RD_RD_RD,
	otawa_kind_SUBFCO_RD_RD_RD,
	otawa_kind_SUBFC__RD_RD_RD,
	otawa_kind_SUBFC_RD_RD_RD,
	otawa_kind_SUBFO__RD_RD_RD,
	otawa_kind_SUBFO_RD_RD_RD,
	otawa_kind_SUBF__RD_RD_RD,
	otawa_kind_SUBF_RD_RD_RD,
	otawa_kind_STWCX__RD_RD_RD,
	otawa_kind_STWBRX_RD_RD_RD,
	otawa_kind_STSWI_RD_RD_D,
	otawa_kind_STSWX_RD_RD_RD,
	otawa_kind_STHBRX_RD_RD_RD,
	otawa_kind_STWUX_RD_RD_RD,
	otawa_kind_STWX_RD_RD_RD,
	otawa_kind_STHUX_RD_RD_RD,
	otawa_kind_STHX_RD_RD_RD,
	otawa_kind_STBUX_RD_RD_RD,
	otawa_kind_STBX_RD_RD_RD,
	otawa_kind_SRW__RD_RD_RD,
	otawa_kind_SRW_RD_RD_RD,
	otawa_kind_SRAWI__RD_RD_D,
	otawa_kind_SRAWI_RD_RD_D,
	otawa_kind_SRAW__RD_RD_RD,
	otawa_kind_SRAW_RD_RD_RD,
	otawa_kind_SLW__RD_RD_RD,
	otawa_kind_SLW_RD_RD_RD,
	otawa_kind_ORC__RD_RD_RD,
	otawa_kind_ORC_RD_RD_RD,
	otawa_kind_OR__RD_RD_RD,
	otawa_kind_OR_RD_RD_RD,
	otawa_kind_MTSPR_D_RD,
	otawa_kind_MTMSR_RD,
	otawa_kind_MFSPR_RD_D,
	otawa_kind_MFMSR_RD,
	otawa_kind_NOR__RD_RD_RD,
	otawa_kind_NOR_RD_RD_RD,
	otawa_kind_NEGO__RD_RD,
	otawa_kind_NEGO_RD_RD,
	otawa_kind_NEG__RD_RD,
	otawa_kind_NEG_RD_RD,
	otawa_kind_NAND__RD_RD_RD,
	otawa_kind_NAND_RD_RD_RD,
	otawa_kind_MULLWO__RD_RD_RD,
	otawa_kind_MULLWO_RD_RD_RD,
	otawa_kind_MULLW__RD_RD_RD,
	otawa_kind_MULLW_RD_RD_RD,
	otawa_kind_MULHWU__RD_RD_RD,
	otawa_kind_MULHWU_RD_RD_RD,
	otawa_kind_MULHW__RD_RD_RD,
	otawa_kind_MULHW_RD_RD_RD,
	otawa_kind_MTSPR_S_RD,
	otawa_kind_MCRXR_CRFD,
	otawa_kind_MTCRF_D_RD,
	otawa_kind_MFSPR_RD_S,
	otawa_kind_LWARX_RD_RD_RD,
	otawa_kind_LWBRX_RD_RD_RD,
	otawa_kind_LWZUX_RD_RD_RD,
	otawa_kind_LWZX_RD_RD_RD,
	otawa_kind_LHZUX_RD_RD_RD,
	otawa_kind_LHZX_RD_RD_RD,
	otawa_kind_LHBRX_RD_RD_RD,
	otawa_kind_LHAUX_RD_RD_RD,
	otawa_kind_LHAX_RD_RD_RD,
	otawa_kind_LBZUX_RD_RD_RD,
	otawa_kind_LBZX_RD_RD_RD,
	otawa_kind_ISEL_RD__RD__R5B__D,
	otawa_kind_EXTSH__RD_RD,
	otawa_kind_EXTSH_RD_RD,
	otawa_kind_EXTSB__RD_RD,
	otawa_kind_EXTSB_RD_RD,
	otawa_kind_EQV__RD_RD_RD,
	otawa_kind_EQV_RD_RD_RD,
	otawa_kind_DIVWUO__RD_RD_RD,
	otawa_kind_DIVWUO_RD_RD_RD,
	otawa_kind_DIVWU__RD_RD_RD,
	otawa_kind_DIVWU_RD_RD_RD,
	otawa_kind_DIVWO__RD_RD_RD,
	otawa_kind_DIVWO_RD_RD_RD,
	otawa_kind_DIVW__RD_RD_RD,
	otawa_kind_DIVW_RD_RD_RD,
	otawa_kind_CNTLZW__RD__RD,
	otawa_kind_CNTLZW_RD__RD,
	otawa_kind_CMPL_D_D_RD_RD,
	otawa_kind_CMP_D_D_RD_RD,
	otawa_kind_ANDC__RD_RD_RD,
	otawa_kind_ANDC_RD_RD_RD,
	otawa_kind_AND__RD_RD_RD,
	otawa_kind_AND_RD_RD_RD,
	otawa_kind_ADDZEO__RD_RD,
	otawa_kind_ADDZEO_RD_RD,
	otawa_kind_ADDZE__RD_RD,
	otawa_kind_ADDZE_RD_RD,
	otawa_kind_ADDMEO__RD_RD,
	otawa_kind_ADDMEO_RD_RD,
	otawa_kind_ADDME__RD_RD,
	otawa_kind_ADDME_RD_RD,
	otawa_kind_ADDEO__RD_RD_RD,
	otawa_kind_ADDEO_RD_RD_RD,
	otawa_kind_ADDE__RD_RD_RD,
	otawa_kind_ADDE_RD_RD_RD,
	otawa_kind_ADDCO__RD_RD_RD,
	otawa_kind_ADDCO_RD_RD_RD,
	otawa_kind_ADDC__RD_RD_RD,
	otawa_kind_ADDC_RD_RD_RD,
	otawa_kind_ADDSS_RD_RD_RD,
	otawa_kind_E_XORIS_RD__RD__X,
	otawa_kind_E_SUBFICS_RD__RD__D,
	otawa_kind_E_STMW_RD__D_LP_RD_RP_,
	otawa_kind_E_STWU_RD__D_LP_RD_RP_,
	otawa_kind_E_STW_RD__D_LP_RD_RP_,
	otawa_kind_E_STHU_RD__D_LP_RD_RP_,
	otawa_kind_E_STH_RD__D_LP_RD_RP_,
	otawa_kind_E_STBU_RD__D_LP_RD_RP_,
	otawa_kind_E_STB_RD__D_LP_RD_RP_,
	otawa_kind_E_SRWIS_RD__RD__D,
	otawa_kind_E_SLWIS_RD__RD__D,
	otawa_kind_E_RLWINM_RD__RD__D__D__D,
	otawa_kind_E_RLWIMI_RD__RD__D__D__D,
	otawa_kind_E_RLWIS_RD__RD__D,
	otawa_kind_E_RLWS_RD__RD__RD,
	otawa_kind_E_ORIS_RD__RD__X,
	otawa_kind_E_OR2IS_RD__X,
	otawa_kind_E_OR2I_RD__X,
	otawa_kind_E_MULL2I_RD__D,
	otawa_kind_E_MULLI_RD__RD__D,
	otawa_kind_E_MCRF_CRD__CRD,
	otawa_kind_E_LMW_RD__D_LP_RD_RP_,
	otawa_kind_E_LWZU_RD__D_LP_RD_RP_,
	otawa_kind_E_LWZ_RD__D_LP_RD_RP_,
	otawa_kind_E_LIS_RD__X,
	otawa_kind_E_LI_RD__X,
	otawa_kind_E_LHZU_RD__D_LP_RD_RP_,
	otawa_kind_E_LHZ_RD__D_LP_RD_RP_,
	otawa_kind_E_LHAU_RD__D_LP_RD_RP_,
	otawa_kind_E_LHA_RD__D_LP_RD_RP_,
	otawa_kind_E_LBZU_RD__D_LP_RD_RP_,
	otawa_kind_E_LBZ_RD__D_LP_RD_RP_,
	otawa_kind_E_CRXOR_CRBD__CRBD__CRBD,
	otawa_kind_E_CRORC_CRBD__CRBD__CRBD,
	otawa_kind_E_CROR_CRBD__CRBD__CRBD,
	otawa_kind_E_CRNOR_CRBD__CRBD__CRBD,
	otawa_kind_E_CRNAND_CRBD__CRBD__CRBD,
	otawa_kind_E_CREQV_CRBD__CRBD__CRBD,
	otawa_kind_E_CRANDC_CRBD__CRBD__CRBD,
	otawa_kind_E_CRAND_CRBD__CRBD__CRBD,
	otawa_kind_E_CMPLI_CRD__RD__D,
	otawa_kind_E_CMPL16I_RD__D,
	otawa_kind_E_CMPI_CRD__RD__D,
	otawa_kind_E_CMPHL16I_RD__D,
	otawa_kind_E_CMPHL_CRD__RD__RD,
	otawa_kind_E_CMPH16I_RD__D,
	otawa_kind_E_CMPH_CRD__RD__RD,
	otawa_kind_E_CMP16I_RD__D,
	otawa_kind_E_BCS_X__X_08X,
	otawa_kind_E_BS_08X,
	otawa_kind_E_ADDICS_RD__RD__D,
	otawa_kind_E_AND2IS__RD__D,
	otawa_kind_E_AND2I__RD__D,
	otawa_kind_E_ADDICS_RD__RD__D_0,
	otawa_kind_E_ADDIS_RD__RD__D,
	otawa_kind_E_ADD2IS_RD__D,
	otawa_kind_E_ADD2I__RD__D,
	otawa_kind_E_ADD16I_RD__RD__D,
	otawa_kind_SE_SUBIS_RD__D,
	otawa_kind_SE_SUBF_RD__RD,
	otawa_kind_SE_SUB_RD__RD,
	otawa_kind_SE_STW_RD__D_LP_RD_RP_,
	otawa_kind_SE_STH_RD__D_LP_RD_RP_,
	otawa_kind_SE_STB_RD__D_LP_RD_RP_,
	otawa_kind_SE_SRWI_RD__D,
	otawa_kind_SE_SRW_RD__RD,
	otawa_kind_SE_SRAWI_RD__D,
	otawa_kind_SE_SRAW_RD__RD,
	otawa_kind_SE_SLWI_RD__D,
	otawa_kind_SE_SLW_RD__RD,
	otawa_kind_SE_SC,
	otawa_kind_SE_RFI,
	otawa_kind_SE_RFDI,
	otawa_kind_SE_RFCI,
	otawa_kind_SE_OR_RD__RD,
	otawa_kind_SE_NOT_RD,
	otawa_kind_SE_NEG_RD,
	otawa_kind_SE_MULLW_RD__RD,
	otawa_kind_SE_MTLR_RD,
	otawa_kind_SE_MTCTR_RD,
	otawa_kind_SE_MTAR_RD__RD,
	otawa_kind_SE_MR_RD__RD,
	otawa_kind_SE_MFLR_RD,
	otawa_kind_SE_MFCTR_RD,
	otawa_kind_SE_MFAR_RD__RD,
	otawa_kind_SE_LI_RD__D,
	otawa_kind_SE_LWZ_RD__D_LP_RD_RP_,
	otawa_kind_SE_LHZ_RD__D_LP_RD_RP_,
	otawa_kind_SE_LBZ_RD__D_LP_RD_RP_,
	otawa_kind_SE_EXTZH_RD,
	otawa_kind_SE_EXTZB_RD,
	otawa_kind_SE_EXTSH_RD,
	otawa_kind_SE_EXTSB_RD,
	otawa_kind_SE_CMPLI_RD__D,
	otawa_kind_SE_CMPL_RD__RD,
	otawa_kind_SE_CMPI_RD__D,
	otawa_kind_SE_CMPHL_RD__RD,
	otawa_kind_SE_CMPH_RD__RD,
	otawa_kind_SE_CMP_RD__RD,
	otawa_kind_SE_BTSTI_RD__D,
	otawa_kind_SE_BSETI_RD__D,
	otawa_kind_SE_BMSKI_RD__D,
	otawa_kind_BLRS,
	otawa_kind_BGENI_RD__D,
	otawa_kind_SE_BCTRS,
	otawa_kind_BCLRI_RD__D,
	otawa_kind_SE_BC_X__X__08X,
	otawa_kind_SE_BS_08X,
	otawa_kind_SE_ANDC_RD__RD,
	otawa_kind_SE_ANDI_RD__D,
	otawa_kind_E_ANDS_RD__RD_,
	otawa_kind_SE_ADDI_RD__D,
	otawa_kind_SE_ADD_RD_RD,
	otawa_kind_MFAPIDI_RD__RD,
	otawa_kind_TLBSYNC_0,
	otawa_kind_TLBIE_RD,
	otawa_kind_TLBIA,
	otawa_kind_RFI,
	otawa_kind_MTSRIN_RD_RD,
	otawa_kind_MTSR_D_RD,
	otawa_kind_MFSRIN_RD_RD,
	otawa_kind_MFSR_RD_D,
	otawa_kind_MTSPR_D_RD_0,
	otawa_kind_MTMSR_RD_0,
	otawa_kind_MFSPR_RD_D_0,
	otawa_kind_MFMSR_RD_0,
	otawa_kind_MFTB_RD_D,
	otawa_kind_ISYNC,
	otawa_kind_EIEIO,
	otawa_kind_ECOWX_RD_RD_RD,
	otawa_kind_ECIWX_RD_RD_RD,
	otawa_kind_ICBI_RD_RD_0,
	otawa_kind_DCBZ_RD_RD_0,
	otawa_kind_DCBTST_RD_RD_0,
	otawa_kind_DCBT_RD_RD_0,
	otawa_kind_DCBST_RD_RD_0,
	otawa_kind_DCBI_RD__RD_0,
	otawa_kind_DCBF_RD__RD_0,
	otawa_kind_DCBA_RD_RD_0,
	otawa_kind_MTFSFI__CRFD_D,
	otawa_kind_MTFSFI_CRFD_D,
	otawa_kind_MTFSF__D_FRD,
	otawa_kind_MTFSF_D_FRD,
	otawa_kind_MTFSB1__CRBD,
	otawa_kind_MTFSB1_CRBD,
	otawa_kind_MTFSB0__CRBD,
	otawa_kind_MTFSB0_CRBD,
	otawa_kind_MFFS__FRD,
	otawa_kind_MFFS_FRD,
	otawa_kind_MCRFS_CRFD_CRFD,
	otawa_kind_FCTIWZ__FRD_FRD,
	otawa_kind_FCTIWZ_FRD_FRD,
	otawa_kind_FCTIW__FRD_FRD,
	otawa_kind_FCTIW_FRD_FRD,
	otawa_kind_FRSP__FRD_FRD,
	otawa_kind_FRSP_FRD_FRD,
	otawa_kind_FNABS__FRD_FRD,
	otawa_kind_FNABS_FRD_FRD,
	otawa_kind_FABS__FRD_FRD,
	otawa_kind_FABS_FRD_FRD,
	otawa_kind_FNEG__FRD_FRD,
	otawa_kind_FNEG_FRD_FRD,
	otawa_kind_FMR__FRD_FRD,
	otawa_kind_FMR_FRD_FRD,
	otawa_kind_FCMPU_CRFD_FRD_FRD,
	otawa_kind_FCMPO_CRFD_FRD_FRD,
	otawa_kind_FNMSUBS__FRD_FRD_FRD_FRD,
	otawa_kind_FNMSUBS_FRD_FRD_FRD_FRD,
	otawa_kind_FNMSUB__FRD_FRD_FRD_FRD,
	otawa_kind_FNMSUB_FRD_FRD_FRD_FRD,
	otawa_kind_FMSUBS__FRD_FRD_FRD_FRD,
	otawa_kind_FMSUBS_FRD_FRD_FRD_FRD,
	otawa_kind_FMSUB__FRD_FRD_FRD_FRD,
	otawa_kind_FMSUB_FRD_FRD_FRD_FRD,
	otawa_kind_FNMADDS__FRD_FRD_FRD_FRD,
	otawa_kind_FNMADDS_FRD_FRD_FRD_FRD,
	otawa_kind_FNMADD__FRD_FRD_FRD_FRD,
	otawa_kind_FNMADD_FRD_FRD_FRD_FRD,
	otawa_kind_FMADDS__FRD_FRD_FRD_FRD,
	otawa_kind_FMADDS_FRD_FRD_FRD_FRD,
	otawa_kind_FMADD__FRD_FRD_FRD_FRD,
	otawa_kind_FMADD_FRD_FRD_FRD_FRD,
	otawa_kind_FDIVS__FRD_FRD_FRD,
	otawa_kind_FDIVS_FRD_FRD_FRD,
	otawa_kind_FDIV__FRD_FRD_FRD,
	otawa_kind_FDIV_FRD_FRD_FRD,
	otawa_kind_FMULS__FRD_FRD_FRD,
	otawa_kind_FMULS_FRD_FRD_FRD,
	otawa_kind_FMUL__FRD_FRD_FRD,
	otawa_kind_FMUL_FRD_FRD_FRD,
	otawa_kind_FSUBS__FRD_FRD_FRD,
	otawa_kind_FSUBS_FRD_FRD_FRD,
	otawa_kind_FSUB__FRD_FRD_FRD,
	otawa_kind_FSUB_FRD_FRD_FRD,
	otawa_kind_FADDS__FRD_FRD_FRD,
	otawa_kind_FADDS_FRD_FRD_FRD,
	otawa_kind_FADD__FRD_FRD_FRD,
	otawa_kind_FADD_FRD_FRD_FRD,
	otawa_kind_STFSUX_FRD_RD_RD,
	otawa_kind_STFSU_FRD_D_LP_RD_RP_,
	otawa_kind_STFSX_FRD_RD_RD,
	otawa_kind_STFS_FRD_D_LP_RD_RP_,
	otawa_kind_STFDUX_FRD_RD_RD,
	otawa_kind_STFDU_FRD_D_LP_RD_RP_,
	otawa_kind_STFDX_FRD_RD_RD,
	otawa_kind_STFD_FRD_D_LP_RD_RP_,
	otawa_kind_LFSUX_FRD_RD_RD,
	otawa_kind_LFSU_FRD_D_LP_RD_RP_,
	otawa_kind_LFSX_FRD_RD_RD,
	otawa_kind_LFS_FRD_D_LP_RD_RP_,
	otawa_kind_LFDUX_FRD_RD_RD,
	otawa_kind_LFDU_FRD_D_LP_RD_RP_,
	otawa_kind_LFDX_FRD_RD_RD,
	otawa_kind_LFD_FRD_D_LP_RD_RP_,
	otawa_kind_TWI_D_RD_D,
	otawa_kind_TW_D_RD_RD_0,
	otawa_kind_SYNC,
	otawa_kind_STWCX__RD_RD_RD_0,
	otawa_kind_LWARX_RD_RD_RD_0,
	otawa_kind_MFSPR_RD_S_0,
	otawa_kind_MTSPR_S_RD_0,
	otawa_kind_MFCR_RD_0,
	otawa_kind_ISEL_RD__RD__R5B__D_0,
	otawa_kind_MCRXR_CRFD_0,
	otawa_kind_MTCRF_D_RD_0,
	otawa_kind_MCRF_CRFD_CRFD,
	otawa_kind_CRORC_CRBD_CRBD_CRBD,
	otawa_kind_CRANDC_CRBD_CRBD_CRBD,
	otawa_kind_CREQV_CRBD_CRBD_CRBD,
	otawa_kind_CRNOR_CRBD_CRBD_CRBD,
	otawa_kind_CRNAND_CRBD_CRBD_CRBD,
	otawa_kind_CRXOR_CRBD_CRBD_CRBD,
	otawa_kind_CROR_CRBD_CRBD_CRBD,
	otawa_kind_CRAND_CRBD_CRBD_CRBD,
	otawa_kind_SRAW__RD_RD_RD_0,
	otawa_kind_SRAW_RD_RD_RD_0,
	otawa_kind_SRAWI__RD_RD_D_0,
	otawa_kind_SRAWI_RD_RD_D_0,
	otawa_kind_SRW__RD_RD_RD_0,
	otawa_kind_SRW_RD_RD_RD_0,
	otawa_kind_SLW__RD_RD_RD_0,
	otawa_kind_SLW_RD_RD_RD_0,
	otawa_kind_RLWIMI__RD_RD_D_D_D,
	otawa_kind_RLWIMI_RD_RD_D_D_D,
	otawa_kind_RLWNM__RD_RD_RD_D_D,
	otawa_kind_RLWNM_RD_RD_RD_D_D,
	otawa_kind_RLWINM__RD_RD_D_D_D,
	otawa_kind_RLWINM_RD_RD_D_D_D,
	otawa_kind_CNTLZW__RD__RD_0,
	otawa_kind_CNTLZW_RD__RD_0,
	otawa_kind_EXTSH__RD_RD_0,
	otawa_kind_EXTSH_RD_RD_0,
	otawa_kind_EXTSB__RD_RD_0,
	otawa_kind_EXTSB_RD_RD_0,
	otawa_kind_EQV__RD_RD_RD_0,
	otawa_kind_EQV_RD_RD_RD_0,
	otawa_kind_NAND__RD_RD_RD_0,
	otawa_kind_NAND_RD_RD_RD_0,
	otawa_kind_NOR__RD_RD_RD_0,
	otawa_kind_NOR_RD_RD_RD_0,
	otawa_kind_XORIS_RD_RD_D,
	otawa_kind_XORI_RD_RD_D,
	otawa_kind_XOR__RD_RD_RD_0,
	otawa_kind_XOR_RD_RD_RD_0,
	otawa_kind_ANDC__RD_RD_RD_0,
	otawa_kind_ANDC_RD_RD_RD_0,
	otawa_kind_ANDIS__RD_RD_D,
	otawa_kind_ANDI__RD_RD_D,
	otawa_kind_AND__RD_RD_RD_0,
	otawa_kind_AND_RD_RD_RD_0,
	otawa_kind_ORC__RD_RD_RD_0,
	otawa_kind_ORC_RD_RD_RD_0,
	otawa_kind_ORIS_RD_RD_D,
	otawa_kind_ORI_RD_RD_D,
	otawa_kind_OR__RD_RD_RD_0,
	otawa_kind_OR_RD_RD_RD_0,
	otawa_kind_CMPL_D_D_RD_RD_0,
	otawa_kind_CMPLI_D_D_RD_D,
	otawa_kind_CMP_D_D_RD_RD_0,
	otawa_kind_CMPI_D_D_RD_D,
	otawa_kind_NEGO__RD_RD_0,
	otawa_kind_NEGO_RD_RD_0,
	otawa_kind_NEG__RD_RD_0,
	otawa_kind_NEG_RD_RD_0,
	otawa_kind_DIVWUO__RD_RD_RD_0,
	otawa_kind_DIVWUO_RD_RD_RD_0,
	otawa_kind_DIVWU__RD_RD_RD_0,
	otawa_kind_DIVWU_RD_RD_RD_0,
	otawa_kind_DIVWO__RD_RD_RD_0,
	otawa_kind_DIVWO_RD_RD_RD_0,
	otawa_kind_DIVW__RD_RD_RD_0,
	otawa_kind_DIVW_RD_RD_RD_0,
	otawa_kind_MULHWU__RD_RD_RD_0,
	otawa_kind_MULHWU_RD_RD_RD_0,
	otawa_kind_MULHW__RD_RD_RD_0,
	otawa_kind_MULHW_RD_RD_RD_0,
	otawa_kind_MULLI_RD_RD_D,
	otawa_kind_MULLWO__RD_RD_RD_0,
	otawa_kind_MULLWO_RD_RD_RD_0,
	otawa_kind_MULLW__RD_RD_RD_0,
	otawa_kind_MULLW_RD_RD_RD_0,
	otawa_kind_SUBFZEO__RD_RD_0,
	otawa_kind_SUBFZEO_RD_RD_0,
	otawa_kind_SUBFZE__RD_RD_0,
	otawa_kind_SUBFZE_RD_RD_0,
	otawa_kind_SUBFMEO__RD_RD_0,
	otawa_kind_SUBFMEO_RD_RD_0,
	otawa_kind_SUBFME__RD_RD_0,
	otawa_kind_SUBFME_RD_RD_0,
	otawa_kind_SUBFEO__RD_RD_RD_0,
	otawa_kind_SUBFEO_RD_RD_RD_0,
	otawa_kind_SUBFE__RD_RD_RD_0,
	otawa_kind_SUBFE_RD_RD_RD_0,
	otawa_kind_SUBFCO__RD_RD_RD_0,
	otawa_kind_SUBFCO_RD_RD_RD_0,
	otawa_kind_SUBFC__RD_RD_RD_0,
	otawa_kind_SUBFC_RD_RD_RD_0,
	otawa_kind_SUBFIC_RD_RD_D,
	otawa_kind_SUBFO__RD_RD_RD_0,
	otawa_kind_SUBFO_RD_RD_RD_0,
	otawa_kind_SUBF__RD_RD_RD_0,
	otawa_kind_SUBF_RD_RD_RD_0,
	otawa_kind_ADDZEO__RD_RD_0,
	otawa_kind_ADDZEO_RD_RD_0,
	otawa_kind_ADDZE__RD_RD_0,
	otawa_kind_ADDZE_RD_RD_0,
	otawa_kind_ADDMEO__RD_RD_0,
	otawa_kind_ADDMEO_RD_RD_0,
	otawa_kind_ADDME__RD_RD_0,
	otawa_kind_ADDME_RD_RD_0,
	otawa_kind_ADDEO__RD_RD_RD_0,
	otawa_kind_ADDEO_RD_RD_RD_0,
	otawa_kind_ADDE__RD_RD_RD_0,
	otawa_kind_ADDE_RD_RD_RD_0,
	otawa_kind_ADDCO__RD_RD_RD_0,
	otawa_kind_ADDCO_RD_RD_RD_0,
	otawa_kind_ADDC__RD_RD_RD_0,
	otawa_kind_ADDC_RD_RD_RD_0,
	otawa_kind_ADDIC__RD_RD_D,
	otawa_kind_ADDIC_RD_RD_D,
	otawa_kind_ADDIS_RD_RD_D,
	otawa_kind_ADDI_RD_RD_D,
	otawa_kind_ADDSS_RD_RD_RD_0,
	otawa_kind_STSWX_RD_RD_RD_0,
	otawa_kind_STSWI_RD_RD_D_0,
	otawa_kind_STMW_RD_D_LP_RD_RP_,
	otawa_kind_STWBRX_RD_RD_RD_0,
	otawa_kind_STHBRX_RD_RD_RD_0,
	otawa_kind_STWUX_RD_RD_RD_0,
	otawa_kind_STWU_RD_D_LP_RD_RP_,
	otawa_kind_STWX_RD_RD_RD_0,
	otawa_kind_STW_RD_D_LP_RD_RP_,
	otawa_kind_STHUX_RD_RD_RD_0,
	otawa_kind_STHU_RD_D_LP_RD_RP_,
	otawa_kind_STHX_RD_RD_RD_0,
	otawa_kind_STH_RD_D_LP_RD_RP_,
	otawa_kind_STBUX_RD_RD_RD_0,
	otawa_kind_STBU_RD_D_LP_RD_RP_,
	otawa_kind_STBX_RD_RD_RD_0,
	otawa_kind_STB_RD_D_LP_RD_RP_,
	otawa_kind_LSWX_RD_RD_RD,
	otawa_kind_LSWI_RD_RD_D,
	otawa_kind_LMW_RD_D_LP_RD_RP_,
	otawa_kind_LWBRX_RD_RD_RD_0,
	otawa_kind_LHBRX_RD_RD_RD_0,
	otawa_kind_LWZUX_RD_RD_RD_0,
	otawa_kind_LWZU_RD_D_LP_RD_RP_,
	otawa_kind_LWZX_RD_RD_RD_0,
	otawa_kind_LWZ_RD_D_LP_RD_RP_,
	otawa_kind_LHAUX_RD_RD_RD_0,
	otawa_kind_LHAU_RD_D_LP_RD_RP_,
	otawa_kind_LHAX_RD_RD_RD_0,
	otawa_kind_LHA_RD_D_LP_RD_RP_,
	otawa_kind_LHZUX_RD_RD_RD_0,
	otawa_kind_LHZU_RD_D_LP_RD_RP_,
	otawa_kind_LHZX_RD_RD_RD_0,
	otawa_kind_LHZ_RD_D_LP_RD_RP_,
	otawa_kind_LBZUX_RD_RD_RD_0,
	otawa_kind_LBZU_RD_D_LP_RD_RP_,
	otawa_kind_LBZX_RD_RD_RD_0,
	otawa_kind_LBZ_RD_D_LP_RD_RP_,
	otawa_kind_SC,
	otawa_kind_BCLRL_D_D,
	otawa_kind_BCLR_D_D,
	otawa_kind_BCCTRL_D_D,
	otawa_kind_BCCTR_D_D,
	otawa_kind_BCLA_D_D_D,
	otawa_kind_BCL_D_D_D,
	otawa_kind_BCA_D_D_D,
	otawa_kind_BC_D_D_D,
	otawa_kind_BLA_D,
	otawa_kind_BL_0X08X,
	otawa_kind_BA_D,
	otawa_kind_B_D
};

/**
 * Get the OTAWA kind of the instruction.
 * @return OTAWA kind.
 */
otawa_kind_t ppc_kind(ppc_inst_t *inst) {
	return kind_funs[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif
