/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

#include <$(proc)/api.h>
#include <$(proc)/id.h>
#include <$(proc)/macros.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint32_t otawa_target_t;

typedef otawa_target_t (*target_fun_t)($(proc)_inst_t *inst);



static otawa_target_t otawa_target_UNKNOWN($(proc)_inst_t *inst)
{
        /* this code should also be used as default value if
        an instruction has no otawa_target field */
        return 0;
}

$(foreach instructions)
static otawa_target_t otawa_target_$(IDENT)($(proc)_inst_t *inst) {
$(otawa_target)
};

$(end)


/* function table */
static target_fun_t $(proc)_target_table[] =
{
	otawa_target_UNKNOWN$(foreach instructions),
	otawa_target_$(IDENT)$(end)
};



/**
 * Get the OTAWA target of the instruction.
 * @return OTAWA target.
 */
otawa_target_t $(proc)_target(ppc_inst_t *inst)
{
        return $(proc)_target_table[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif

