/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

#include <$(proc)/api.h>
#include <$(proc)/id.h>
#include <$(proc)/macros.h>
#include <$(proc)/grt.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef int (*pred_fun_t)($(proc)_inst_t *inst);

/*** function definition ***/

static int otawa_pred_UNKNOWN($(proc)_inst_t *inst) {
	return -1;
}

$(foreach instructions)
static int otawa_pred_$(IDENT)($(proc)_inst_t *inst) {
$(otawa_pred)
};

$(end)


/*** function table ***/
static pred_fun_t pred_funs[] = {
	otawa_pred_UNKNOWN$(foreach instructions),
	otawa_pred_$(IDENT)$(end)
};

/**
 * Get the OTAWA static prediction of the instruction.
 * @return OTAWA static prediction.
 */
int $(proc)_pred($(proc)_inst_t *inst) {
	return pred_funs[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif
