/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef PPC_PPC_INCLUDE_PPC_CODE_H
#define PPC_PPC_INCLUDE_PPC_CODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif


#define PPC_CODE_STATE
#define PPC_CODE_INIT(s)
#define PPC_CODE_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* PPC_PPC_INCLUDE_PPC_CODE_H */
