/* Generated by gep (117/07/07 15:08:30) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_PPC_INCLUDE_PPC_DECODE_H
#define GLISS_PPC_INCLUDE_PPC_DECODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif

#define PPC_DECODE_STATE
#define PPC_DECODE_INIT(s)
#define PPC_DECODE_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_PPC_INCLUDE_PPC_DECODE_H */
